// Search aliases for the ingredient picker (NOT displayed for matching, phonetic IS shown as subtitle).
// Phonetic Tamil romanization (thakkaali, kaththarikkaay...) + translated English, per Tamil name.
export const INGREDIENT_ALIASES = {
  'அகத்திக்கீரை': 'akaththikkeerai | agathi keerai',
  'அச்சு வெல்லம்': 'assu vellam | achhu vellam',
  'அஜினோமோட்டோ': 'ajinoamoattoa | ajinomotto',
  'அத்திப்பழம்': 'aththippazham | fig',
  'அனில் திணை சேமியா': 'anil thinai saemiyaa | anil thinai vermicilli',
  'அனில் வரகு சேமியா': 'anil varaku saemiyaa | anil varagu vermicelli',
  'அன்னாசிப் பூ': 'annaasip poo | annasi poo | star anise',
  'அன்னாசிப்பழம்': 'annaasippazham | pineapple',
  'அப்பா தட்டு': 'appaa thattu | appa plate',
  'அமுல் உப்பு இல்லாத வெண்ணெய்': 'amul uppu illaatha venney | amul butter (saltless)',
  'அமுல் சீஸ்': 'amul sees | amul cheese',
  'அமுல் மஞ்சள் வெண்ணெய்': 'amul manjsal venney | amul butter yellow',
  'அமுல் மில்க்மெய்ட்': 'amul milkmeyt | amul milk maid',
  'அமெரிக்கன் சீசனிங் பொடி': 'amerikkan seesaning poti | dp - american seasoning powder',
  'அரிசி - IR 20': 'arisi - IR 20 | rice - ir 20',
  'அரிசி - இட்லி அரிசி (IR 20)': 'arisi - itli arisi (IR 20) | rice - idlyrice (ir 20)',
  'அரிசி - கவுனி': 'arisi - kavuni | rice - kavuni',
  'அரிசி - குறுவை': 'arisi - kuruvai | rice - kuruvai',
  'அரிசி - சீரக சம்பா': 'arisi - seeraka sampaa | rice - seerga samba',
  'அரிசி - டிபன் அரிசி': 'arisi - tipan arisi | rice-tiffin rice',
  'அரிசி - பணியார அரிசி': 'arisi - paniyaara arisi | rice - paniyara',
  'அரிசி - பாஸ்மதி': 'arisi - paasmathi | rice - basmathi',
  'அரிசி - பொன்னி பச்சரிசி': 'arisi - ponni passarisi | rice - ponni paccharisi',
  'அரிசி - பொன்னி புழுங்கல்': 'arisi - ponni puzhungkal | rice - ponni puzhangal',
  'அரிசி உப்புமா மாவு': 'arisi uppumaa maavu | dp - rice upma flour',
  'அரைக்கீரை': 'araikkeerai | arai keerai',
  'அவரைக்காய்': 'avaraikkaay | broad beans',
  'அவல்': 'aval | aval',
  'ஆச்சி மசாலா கோபி 65': 'aassi masaalaa koapi 65 | achi masala gobi 65',
  'ஆந்திரா சாம்பார் காரம்': 'aanthiraa saampaar kaaram | dp - andhra sambar karam',
  'ஆப்பிள்': 'aappil | apple',
  'ஆப்பிள் சைடர் வினிகர்': 'aappil saitar vinikar | apple cider vinegar',
  'ஆம்சூர் பொடி': 'aamsoor poti | dp-amchur powder',
  'ஆவின் தயிர்': 'aavin thayir | aavin curd',
  'ஆவின் பால் பொடி': 'aavin paal poti | aavin milk powder',
  'இஞ்சி': 'injsi | ginger',
  'இஞ்சி பொடி': 'injsi poti | dp - ginger powder',
  'இடியாப்ப மாவு': 'itiyaappa maavu | dp - idiyappa ma',
  'இட்லி பொடி': 'itli poti | dp - idli powder',
  'இத்தாலிய மூலிகைகள்': 'iththaaliya moolikaikal | italian herbs',
  'இனிப்பு சோம்பு': 'inippu soampu | sweet sombu',
  'இனிப்பு சோளம்': 'inippu soalam | sweet corn',
  'இலை - வட்ட இலை': 'ilai - vatta ilai | leaf- round ilai',
  'இளநீர்': 'ilaneer | tender coconut',
  'ஈனோ உப்பு': 'eenoa uppu | eno salt',
  'ஈஸ்ட்': 'eest | yeast',
  'உஜாலா கத்தரிக்காய்': 'ujaalaa kaththarikkaay | brinjal ujala',
  'உருளைக்கிழங்கு (மேட்டுப்பாளையம்)': 'urulaikkizhangku (maettuppaalaiyam) | potato( mettupalayam)',
  'உருளைக்கிழங்கு சிப்ஸ்': 'urulaikkizhangku sips | potato chips',
  'உருளைக்கிழங்கு ஸ்டார்ச்': 'urulaikkizhangku staars | dp - potato starch',
  'உறைந்த பட்டாணி': 'uraintha pattaani | frozen peas',
  'உலர் சோயா பீன்ஸ்': 'ular soayaa peens | dry soya beans',
  'உலர் டபுள் பீன்ஸ்': 'ular tapul peens | dry double beans',
  'உலர் பச்சைப் பட்டாணி': 'ular passaip pattaani | dry pacchai pattani',
  'உலர் பட்டர் பீன்ஸ்': 'ular pattar peens | dry butter beans',
  'உலர் பட்டாணி': 'ular pattaani | dry peas',
  'ஊதா முட்டைக்கோஸ்': 'oothaa muttaikkoas | violet cabbage',
  'ஊறுகாய் - இஞ்சி தொக்கு': 'oorukaay - injsi thokku | pickle - ginger thokku',
  'ஊறுகாய் - இஞ்சி புளி': 'oorukaay - injsi puli | pickle - ginger tamarind',
  'ஊறுகாய் - பூண்டு ஊறுகாய்': 'oorukaay - poontu oorukaay | pickle - garlic pickle',
  'ஊறுகாய் - வெங்காய தொக்கு': 'oorukaay - vengkaaya thokku | pickle - onion thokku',
  'எண்ணெய் - GN நல்லெண்ணெய்': 'enney - GN nallenney | oil - gn sesame oil',
  'எண்ணெய் - எண்ணெய்': 'enney - enney | oil - oil',
  'எண்ணெய் - கடுகு எண்ணெய்': 'enney - katuku enney | oil - mustard oil',
  'எண்ணெய் - தேங்காய் எண்ணெய்': 'enney - thaengkaay enney | oil - coconut oil',
  'எண்ணெய் - நல்லெண்ணெய்': 'enney - nallenney | oil - sesame oil | oil - sesame oil kal',
  'எலுமிச்சை': 'elumissai | lemon',
  'எள் பொடி': 'el poti | ellu podi',
  'ஏடு': 'aetu | yaedu',
  'ஏலக்காய்': 'aelakkaay | cardamom',
  'ஏலக்காய் பொடி': 'aelakkaay poti | dp - cardamom powder',
  'ஏலக்கி வாழைப்பழம்': 'aelakki vaazhaippazham | yelaki banana',
  'ஓட்ஸ்': 'oats | oats',
  'ஓமப்பொடி': 'oamappoti | omapodi',
  'ஓமம்': 'oamam | omam',
  'ஓரிகானோ': 'oarikaanoa | organo',
  'கசகசா': 'kasakasaa | khus khus | poppy seeds',
  'கசூரி மேத்தி': 'kasoori maeththi | kasuri methi',
  'கடலை மாவு': 'katalai maavu | dp - basen | dp - bengal gram flour',
  'கடுகு': 'katuku | kadugu | mustard',
  'கடை ஆவக்காய் மாங்காய் ஊறுகாய்': 'katai aavakkaay maangkaay oorukaay | kadai avakaai mango pickle',
  'கடை எலுமிச்சை ஊறுகாய்': 'katai elumissai oorukaay | kadai lemon pickle',
  'கடை கலவை காய்கறி ஊறுகாய்': 'katai kalavai kaaykari oorukaay | kadai mixed veg. pickle',
  'கடை கொங்குரா ஊறுகாய்': 'katai kongkuraa oorukaay | kadai kongura pickle',
  'கடை கொடாரங்காய் ஊறுகாய்': 'katai kotaarangkaay oorukaay | kadai kodaranga pickle',
  'கடை புளிச்ச கீரை தொக்கு': 'katai pulissa keerai thokku | kadai pulichakeerai thokku',
  'கடை மாங்காய் தொக்கு': 'katai maangkaay thokku | kadai mango thokku',
  'கடை வடுமாங்காய் ஊறுகாய்': 'katai vatumaangkaay oorukaay | kadai vadumango pickle',
  'கம்பு': 'kampu | kambu',
  'கரம் மசாலா': 'karam masaalaa | dp - garam masala',
  'கருஞ்சீரகம்': 'karunjseerakam | kalonji',
  'கருணைக்கிழங்கு': 'karunaikkizhangku | karunai kizhangu',
  'கருப்பட்டி': 'karuppatti | karuppatti',
  'கருப்பட்டி காஜு கட்லி': 'karuppatti kaaju katli | karupatti kaaju kathli',
  'கருப்பு உப்பு': 'karuppu uppu | black salt',
  'கருப்பு எள்': 'karuppu el | black sesame seed',
  'கருப்பு ஏலக்காய்': 'karuppu aelakkaay | black cardamom',
  'கருவேப்பிலை': 'karuvaeppilai | curry leaf',
  'கற்கண்டு': 'karkantu | kalkandu',
  'கலா கோஸ்': 'kalaa koas | kala kos | kalakos',
  'கல் உப்பு': 'kal uppu | crystal salt',
  'கல் பாசி': 'kal paasi | black stone flower',
  'கஸ்டர்ட் பொடி': 'kastart poti | dp - custard powder',
  'காபி பொடி': 'kaapi poti | dp-coffee powder',
  'காராமணி': 'kaaraamani | karamani',
  'கார்ன் ஃப்ளேக்ஸ்': 'kaarn plaeks | corn flakes',
  'கார்ன் ஃப்ளோர்': 'kaarn ploar | dp - corn flour',
  'காலிஃபிளவர்': 'kaalipilavar | cauliflower',
  'காளான்': 'kaalaan | mushroom',
  'காஷ்மீரி மிளகாய் பொடி': 'kaashmeeri milakaay poti | dp - kashmiri chilli powder',
  'கிராம்பு': 'kiraampu | clove',
  'கிஸ்மிஸ்': 'kismis | kismis',
  'கீரை': 'keerai | keerai',
  'குங்குமப்பூ': 'kungkumappoo | saffron',
  'குடிக்கும் சாக்லேட்': 'kutikkum saaklaet | dp - drinking chocolate',
  'குடைமிளகாய்': 'kutaimilakaay | capsicum',
  'குட்டி உருளைக்கிழங்கு': 'kutti urulaikkizhangku | baby potato',
  'குட்டி கத்தரிக்காய்': 'kutti kaththarikkaay | baby brinjal',
  'கும்மாய மாவு': 'kummaaya maavu | dp - kummaya flour',
  'குறு மிளகு': 'kuru milaku | kuru milagu',
  'குறுவை அரிசி மாவு': 'kuruvai arisi maavu | dp - kuruvai rice flour',
  'குல்கந்த்': 'kulkanth | kulkand',
  'கேசரி பொடி': 'kaesari poti | dp - kesari powder',
  'கேப்பை மாவு': 'kaeppai maavu | keppai maa',
  'கேரட்': 'kaerat | carrot',
  'கேழ்வரகு': 'kaezhvaraku | ragi',
  'கேழ்வரகு மாவு': 'kaezhvaraku maavu | ragi maavu',
  'கையுறை': 'kaiyurai | gloves',
  'கொதித்த சீரக எடை': 'kothiththa seeraka etai | kothitha jeera yaedai',
  'கொத்தமல்லி': 'koththamalli | coriander',
  'கொத்தமல்லி இலை': 'koththamalli ilai | coriander leaves | corriender leaf',
  'கொத்தவரங்காய்': 'koththavarangkaay | cluster beans',
  'கொள்ளு': 'kollu | horse gram',
  'கோக்கோ பொடி': 'koakkoa poti | dp - cocoa powder',
  'கோதாஸ் காபி பொடி': 'koathaas kaapi poti | cothas coffee powder',
  'கோதுமை': 'koathumai | wheat',
  'கோதுமை தலியா': 'koathumai thaliyaa | wheat dalia',
  'கோதுமை பாஸ்தா': 'koathumai paasthaa | wheat pasta',
  'கோதுமை மாவு': 'koathumai maavu | dp - wheat flour',
  'கோதுமை ரவை': 'koathumai ravai | wheat rava',
  'கோபி வறுவல் மாவு': 'koapi varuval maavu | dp - gobi fry ma',
  'கோவா (இனிப்பு இல்லாதது)': 'koavaa (inippu illaathathu) | kova( sweetless)',
  'கோவைக்காய்': 'koavaikkaay | kovakkai',
  'கோஸ்மல்லி கத்தரிக்காய்': 'koasmalli kaththarikkaay | kosmalli brinjal',
  'சக்கர வரட்டி': 'sakkara varatti | sakkara varatti',
  'சக்கரைவள்ளி': 'sakkaraivalli | sakkaraivalli',
  'சக்கரைவள்ளிக் கிழங்கு': 'sakkaraivallik kizhangku | sweet potato',
  'சம்பா கோதுமை': 'sampaa koathumai | samba wheat',
  'சர்க்கரை': 'sarkkarai | sugar',
  'சர்க்கரை பொடி': 'sarkkarai poti | dp - sugar powder',
  'சாட் மசாலா': 'saat masaalaa | dp - chat masala',
  'சாப்பாட்டு இலை': 'saappaattu ilai | sappattu ilai',
  'சாம்பார் டாப்பிங் பொடி': 'saampaar taapping poti | dp - sambar topping podi',
  'சாம்பார் பொடி': 'saampaar poti | dp - sambar podi',
  'சாஸ் - இனிப்பு மிளகாய் சாஸ்': 'saas - inippu milakaay saas | sauce - sweet chilli sauce',
  'சாஸ் - சிவப்பு மிளகாய் சாஸ்': 'saas - sivappu milakaay saas | sauce - red chilli sauce',
  'சாஸ் - செஷ்வான் சாஸ்': 'saas - seshvaan saas | sauce - schezwan sauce',
  'சாஸ் - சோயா சாஸ்': 'saas - soayaa saas | sauce - soya sauce',
  'சாஸ் - தக்காளி சாஸ்': 'saas - thakkaali saas | sauce - tomato sauce',
  'சாஸ் - பாஸ்தா சாஸ்': 'saas - paasthaa saas | sauce - pasta sauce',
  'சாஸ் - பூண்டு சாஸ்': 'saas - poontu saas | g sauce - garlic sauce',
  'சாஸ் - மயோனெய்ஸ் சாஸ்': 'saas - mayoaneys saas | sauce - mayonaise sauce',
  'சாஸ் - மிளகாய் சாஸ்': 'saas - milakaay saas | sauce - chilli sauce',
  'சாஸ் - மோமோஸ் சாஸ்': 'saas - moamoas saas | g sauce - momos sauce',
  'சாஸ் - வெள்ளை சாஸ்': 'saas - vellai saas | sauce - white sauce',
  'சிங் மசாலா': 'sing masaalaa | ching masala',
  'சின்ன சோள மாவு': 'sinna soala maavu | chinna cholam maavu',
  'சின்ன வெங்காயம்': 'sinna vengkaayam | small onion',
  'சிப்ஸ் உருளைக்கிழங்கு': 'sips urulaikkizhangku | chips potato',
  'சிறிய அப்பளம்': 'siriya appalam | appalam small',
  'சிறுதானியம் - குதிரைவாலி': 'siruthaaniyam - kuthiraivaali | millet - kuthuravali',
  'சிறுதானியம் - கேப்பை': 'siruthaaniyam - kaeppai | millets-keppai',
  'சிறுதானியம் - சாமை': 'siruthaaniyam - saamai | millet - samai',
  'சிறுதானியம் - திணை': 'siruthaaniyam - thinai | millet - thinai',
  'சிறுதானியம் - வரகு': 'siruthaaniyam - varaku | millet - varagu',
  'சிவப்பு அவல்': 'sivappu aval | red aval',
  'சிவப்பு குடைமிளகாய்': 'sivappu kutaimilakaay | red capsuicum',
  'சிவப்பு பூசணிக்காய்': 'sivappu poosanikkaay | red pumpkin',
  'சிவப்பு மிளகாய் பூண்டு வினிகர்': 'sivappu milakaay poontu vinikar | redchilli garlic vinegar',
  'சீசி கார்ன் நகெட்ஸ்': 'seesi kaarn nakets | cheesy corn nuggers',
  'சீரகப் பொடி': 'seerakap poti | dp - jeera powder',
  'சீரகம்': 'seerakam | cumin seeds | jeera',
  'சுக்கு': 'sukku | sukku',
  'சுக்கு மல்லி': 'sukku malli | dp - suku malli',
  'சுண்டைக்காய்': 'suntaikkaay | sundai kai',
  'சுபல் கத்தரிக்காய்': 'supal kaththarikkaay | subal brinjal',
  'சுரைக்காய்': 'suraikkaay | bottle gourd',
  'செர்ரி': 'serri | cherry',
  'செலரி உப்பு': 'selari uppu | celary salt',
  'செஷ்வான் சட்னி (ரிதா அரோரா)': 'seshvaan satni (rithaa aroaraa) | schezwan chutney (rita arora)',
  'சேனைக்கிழங்கு': 'saenaikkizhangku | yam',
  'சேப்பங்கிழங்கு': 'saeppangkizhangku | colacasia',
  'சைனா கிராஸ்': 'sainaa kiraas | g china grass',
  'சோம்பு': 'soampu | anise | sombu',
  'சோம்பு பொடி': 'soampu poti | dp - anise powder',
  'சோயா சங்': 'soayaa sang | soya chunks',
  'சோயா பீன்ஸ்': 'soayaa peens | soya beans',
  'சோயா மாவு': 'soayaa maavu | dp - soy flour',
  'சோள மாவு': 'soala maavu | corn meal',
  'சோள ரவை': 'soala ravai | chola ravai | corn rava',
  'சௌ சௌ': 'sau sau | chow chow',
  'ஜல் ஜீரா': 'jal jeeraa | g jaljira',
  'ஜாதிக்காய்': 'jaathikkaay | nutmeg',
  'ஜாதிக்காய் பொடி': 'jaathikkaay poti | dp - nutmeg powder',
  'ஜாதிப்பத்திரி': 'jaathippaththiri | mace javitri,',
  'ஜாதிப்பத்திரி பொடி': 'jaathippaththiri poti | dp - jadhipathri powder',
  'ஜாம்': 'jaam | jam',
  'டாங்': 'taang | tang',
  'டாடா உப்பு': 'taataa uppu | tata salt',
  'டிபன் தட்டு இலை': 'tipan thattu ilai | tiffin thattu ilai',
  'டூட்டி ஃப்ரூட்டி': 'tootti prootti | tutti frutti',
  'டைமண்ட் கற்கண்டு': 'taimant karkantu | diamond kalkandu',
  'ட்ரூ சேமியா': 'troo saemiyaa | true semia',
  'தக்காளி (நறுக்கியது)': 'thakkaali (narukkiyathu) | tomato(cut)',
  'தக்காளி கெட்சப்': 'thakkaali ketsap | tomato ketchup',
  'தக்காளி தொக்கு': 'thakkaali thokku | tomato thokku',
  'தக்காளி பேஸ்ட்': 'thakkaali paest | tomato paste',
  'தட்டை அவரைக்காய்': 'thattai avaraikkaay | thattai avaraikkai',
  'தட்டைப்பயத்தங்காய்': 'thattaippayaththangkaay | thattapayathangai',
  'தனியா': 'thaniyaa | dhania',
  'தனியா பொடி': 'thaniyaa poti | dp - coriander powder | dp- dhania powder',
  'தயிர்': 'thayir | curd',
  'தர்பூசணி விதை': 'tharpoosani vithai | water melon seeds',
  'தாளிப்பு வடகம்': 'thaalippu vatakam | thalippu vadagam',
  'தேங்காய்': 'thaengkaay | coconut',
  'தேங்காய் கிரீம்': 'thaengkaay kireem | coconut cream',
  'தேங்காய் பால்': 'thaengkaay paal | coconut milk',
  'தேநீர்': 'thaeneer | dp - tea',
  'தேன்': 'thaen | honey',
  'நவீன் நறுக்கிய தக்காளி': 'naveen narukkiya thakkaali | navin tomato cut',
  'நாட்டு சர்க்கரை': 'naattu sarkkarai | nattu sakkarai',
  'நியூட்ரியண்ட் மாவு': 'niyootriyant maavu | dp - nutrient ma',
  'நிலவேம்பு': 'nilavaempu | neelavembu | nilavembu',
  'நீளமான புடலங்காய்': 'neelamaana putalangkaay | long snake gourd',
  'நூடுல்ஸ் - சீன நூடுல்ஸ்': 'nootuls - seena nootuls | noodles - chinese noodles',
  'நூடுல்ஸ் - மேகி நூடுல்ஸ்': 'nootuls - maeki nootuls | noodles - maggie noodles',
  'நூல்கோல்': 'noolkoal | noolkol | turnip',
  'நெய்': 'ney | ghee',
  'பசலைக்கீரை': 'pasalaikkeerai | palak',
  'பச்சரிசி மாவு': 'passarisi maavu | dp - raw rice flour',
  'பச்சை சுக்கினி': 'passai sukkini | zuccini green',
  'பச்சை டபுள் பீன்ஸ்': 'passai tapul peens | fresh double beans',
  'பச்சை பலாக்காய்': 'passai palaakkaay | raw jack fruit',
  'பச்சை மாங்காய்': 'passai maangkaay | raw mango',
  'பச்சை மிளகாய்': 'passai milakaay | green chilli',
  'பச்சை மொச்சை': 'passai mossai | green mochai',
  'பச்சை வேர்க்கடலை': 'passai vaerkkatalai | raw ground nut',
  'பச்சைப் பட்டாணி': 'passaip pattaani | fresh peas',
  'பஜா மசாலா': 'pajaa masaalaa | dp - baja masala',
  'பஜ்ஜி மிளகாய்': 'pajji milakaay | bajji chilli | bajji milagai',
  'பட்டர் பீன்ஸ்': 'pattar peens | butter beans',
  'பட்டை': 'pattai | cinnamon',
  'பனீர்': 'paneer | ktr paneer',
  'பனீர் திராட்சை': 'paneer thiraatsai | paneer grapes',
  'பனை கற்கண்டு': 'panai karkantu | palm kalkandu',
  'பருப்பு - இட்லிக்கான உளுந்து': 'paruppu - itlikkaana ulunthu | dhall - urad (for idly)',
  'பருப்பு - உளுந்து': 'paruppu - ulunthu | dhall - urad',
  'பருப்பு - கடலைப் பருப்பு': 'paruppu - katalaip paruppu | dhall - bengal gram',
  'பருப்பு - கருப்பு உளுந்து': 'paruppu - karuppu ulunthu | dhall - black gram',
  'பருப்பு - கருப்பு கொண்டைக்கடலை': 'paruppu - karuppu kontaikkatalai | dhall - black channa',
  'பருப்பு - சிறிய வெள்ளை கொண்டைக்கடலை': 'paruppu - siriya vellai kontaikkatalai | dhall - small white channa',
  'பருப்பு - சிவப்பு தட்டைப்பயறு': 'paruppu - sivappu thattaippayaru | dhall - thattapayaru red',
  'பருப்பு - தாளிப்புக்கான உளுந்து': 'paruppu - thaalippukkaana ulunthu | dhall - urad for seasoning',
  'பருப்பு - துவரம் பருப்பு': 'paruppu - thuvaram paruppu | dhall - toor dal',
  'பருப்பு - பட்டாணி பருப்பு': 'paruppu - pattaani paruppu | dhall - peas dal',
  'பருப்பு - பாசிப்பயறு': 'paruppu - paasippayaru | dhall - green gram | dhall- pasi payaru',
  'பருப்பு - பாசிப்பருப்பு': 'paruppu - paasipparuppu | dhall - moong dal',
  'பருப்பு - பொட்டுக்கடலை': 'paruppu - pottukkatalai | dhall-pottu kadalai',
  'பருப்பு - மசூர் பருப்பு': 'paruppu - masoor paruppu | dhall - masur dal',
  'பருப்பு - முளைகட்டிய பாசிப்பயறு': 'paruppu - mulaikattiya paasippayaru | dhall - mullaikatta pasipayaru',
  'பருப்பு - மொச்சை': 'paruppu - mossai | dhall - mochai',
  'பருப்பு - ராஜ்மா': 'paruppu - raajmaa | dhall - rajma',
  'பருப்பு - வெள்ளை கொண்டைக்கடலை': 'paruppu - vellai kontaikkatalai | dhall - white channa',
  'பருப்பு - வெள்ளை சோயா': 'paruppu - vellai soayaa | dhall- white soya',
  'பருப்பு - வெள்ளை தட்டைப்பயறு': 'paruppu - vellai thattaippayaru | dhall- white thattai payaru',
  'பருப்புக்கீரை': 'paruppukkeerai | paruppu keerai',
  'பழம் - மாம்பழம்': 'pazham - maampazham | fruit - mango',
  'பழுத்த பச்சை மிளகாய்': 'pazhuththa passai milakaay | riped green chilly',
  'பாகற்காய்': 'paakarkaay | bitter gourd',
  'பாங்கோ பிரெட் தூள்': 'paangkoa piret thool | dp -panko bread crumbs',
  'பாசுந்தி': 'paasunthi | basundhi',
  'பாதாம்': 'paathaam | almond',
  'பாதாம் பிசின்': 'paathaam pisin | badham pisin',
  'பாப்படம்': 'paappatam | papadam',
  'பாப்ரிகா பொடி': 'paaprikaa poti | paprika powder',
  'பாயாசம் காய்ச்சிய அளவு': 'paayaasam kaayssiya alavu | payasam kaichiya alavu',
  'பாரம்பரிய அரிசி - கருங்குறுவை': 'paarampariya arisi - karungkuruvai | t.rice - karunkuruvai',
  'பாரம்பரிய அரிசி - காட்டுயானம்': 'paarampariya arisi - kaattuyaanam | t.rice - kattuyanam',
  'பாரம்பரிய அரிசி - தூயமல்லி அரிசி': 'paarampariya arisi - thooyamalli arisi | tr-thooyamalli rice',
  'பாரம்பரிய அரிசி - நவரா': 'paarampariya arisi - navaraa | t.rice - navara',
  'பாரம்பரிய அரிசி - பூங்கார்': 'paarampariya arisi - poongkaar | t.rice - poongar',
  'பாரம்பரிய அரிசி - மாப்பிள்ளை சம்பா': 'paarampariya arisi - maappillai sampaa | t.rice - mappillai samba',
  'பாரம்பரிய அரிசி - மூங்கில் அரிசி': 'paarampariya arisi - moongkil arisi | t.rice - moongil',
  'பார்லி': 'paarli | barley',
  'பார்ஸ்லி': 'paarsli | parsley',
  'பாலடா': 'paalataa | palada',
  'பால் (பிரவுன் பாக்கெட்)': 'paal (piravun paakket) | milk (brown pack)',
  'பால் - பால்': 'paal - paal | milk - milk',
  'பால் - பால் (ஆரஞ்சு பாக்கெட்)': 'paal - paal (aaranjsu paakket) | milk - milk (orange pack)',
  'பாவ் பன்': 'paav pan | pav bun',
  'பாஸ்தா - ஃபார்ஃபாலே': 'paasthaa - paarpaalae | pasta - farfalle',
  'பாஸ்தா - ஃபுசில்லி': 'paasthaa - pusilli | pasta - fusili',
  'பாஸ்தா - மக்கரோனி': 'paasthaa - makkaroani | pasta - macaroni',
  'பிரவுன் சர்க்கரை': 'piravun sarkkarai | brown sugar',
  'பிரியாணி இலை': 'piriyaani ilai | bay leaf',
  'பிரியாணி இலை பொடி': 'piriyaani ilai poti | dp - bay leaves flour',
  'பிரெட்': 'piret | bread',
  'பிரோக்கோலி': 'piroakkoali | broccoli',
  'பிலாக்கொட்டை': 'pilaakkottai | pilakottai',
  'பீட்சா சீசனிங் பொடி': 'peetsaa seesaning poti | pizza seasoning powder',
  'பீட்ரூட்': 'peetroot | beet root',
  'பீன்ஸ்': 'peens | beans',
  'பீர்க்கங்காய்': 'peerkkangkaay | ridge gourd',
  'புடலங்காய்': 'putalangkaay | snake gourd',
  'புதினா இலை': 'puthinaa ilai | mint leaf',
  'புதிய கிரீம்': 'puthiya kireem | fresh cream',
  'புளி': 'puli | tamarind',
  'புளிக் குழம்பு பொடி': 'pulik kuzhampu poti | dp - puli curry powder',
  'புஷ் சிவப்பு கலர்': 'push sivappu kalar | dp - bush red color',
  'பூசணி விதை': 'poosani vithai | pumpkin seed',
  'பூசணிக்காய்': 'poosanikkaay | ash gourd',
  'பூண்டு': 'poontu | garlic',
  'பூண்டு ஃப்ளேக்ஸ்': 'poontu plaeks | flakes- garlic',
  'பூண்டு பொடி ஊறுகாய்': 'poontu poti oorukaay | poondu podi pickle',
  'பெங்களூர் புளி': 'pengkaloor puli | bangalore puli',
  'பெரிய அப்பளம்': 'periya appalam | appalam big',
  'பெரிய ரவை': 'periya ravai | big rava',
  'பெருங்காயம்': 'perungkaayam | asfoetida',
  'பேக்கிங் சோடா': 'paekking soataa | dp - baking soda',
  'பேக்கிங் பவுடர்': 'paekking pavutar | dp - baking powder',
  'பேசில்': 'paesil | basil',
  'பேபி கார்ன்': 'paepi kaarn | baby corn',
  'பேபி கார்ன் பெட்டி': 'paepi kaarn petti | baby corn box',
  'பேபி கார்ன், காளான் வறுவல் மாவு': 'paepi kaarn, kaalaan varuval maavu | dp - baby corn,mushroom fry flour',
  'பேரீச்சம் பழம்': 'paereessam pazham | dates',
  'பொடியாக நறுக்கிய பூண்டு': 'potiyaaka narukkiya poontu | poondu podiyaga vettiyadhu',
  'பொட்டுக்கடலை': 'pottukkatalai | fried gram',
  'பொன்னாங்கண்ணி கீரை': 'ponnaangkanni keerai | ponnanganni keerai',
  'பொரி': 'pori | pori',
  'பொரித்த பகோடா': 'poriththa pakoataa | fried pakoda',
  'பொரியல் பொடி': 'poriyal poti | dp - poriyal powder',
  'போர்ன்விட்டா': 'poarnvittaa | dp - bournevita',
  'மக்காச்சோளம்': 'makkaassoalam | makka cholam',
  'மசாலா பால் பொடி': 'masaalaa paal poti | masala paal podi',
  'மஞ்சள் குடைமிளகாய்': 'manjsal kutaimilakaay | yellow capsicum',
  'மஞ்சள் சுக்கினி': 'manjsal sukkini | zuccini yellow',
  'மஞ்சள் பொடி': 'manjsal poti | dp - turmeric powder',
  'மஞ்சூரியன் மாவு': 'manjsooriyan maavu | dp - manchurian flour',
  'மணத்தக்காளி': 'manaththakkaali | manathakkali',
  'மணத்தக்காளி கீரை': 'manaththakkaali keerai | manathakkali keerai',
  'மண்டா வெல்லம்': 'mantaa vellam | manda jaggery',
  'மயோனெய்ஸ்': 'mayoaneys | mayonnaise',
  'மரவள்ளிக்கிழங்கு': 'maravallikkizhangku | topioca',
  'மாங்காய் இஞ்சி': 'maangkaay injsi | mango ginger',
  'மாதுளம்பழம்': 'maathulampazham | pomogranate',
  'மாதுளை பொடி': 'maathulai poti | dp - pomegranate powder',
  'மாதுளை விதை பொடி': 'maathulai vithai poti | dp - anardhana powder',
  'மாவு ஜவ்வரிசி': 'maavu javvarisi | maavu javvurisi',
  'மாஸ் பாதாம் மிக்ஸ்': 'maas paathaam miks | dp - mass almond mix',
  'மில்கி மிஸ்ட் பனீர்': 'milki mist paneer | milky mist panner | milkymist paneer',
  'மிளகாய் - சம்பா மிளகாய்': 'milakaay - sampaa milakaay | chilly - samba chilli',
  'மிளகாய் - சிவப்பு மிளகாய்': 'milakaay - sivappu milakaay | chilly - red chilli',
  'மிளகாய் - சிவப்பு மிளகாய் (புதியது)': 'milakaay - sivappu milakaay (puthiyathu) | chilly - red chilli( new)',
  'மிளகாய் - வட இந்திய மிளகாய்': 'milakaay - vata inthiya milakaay | chilly - north indian chilli',
  'மிளகாய் பொடி': 'milakaay poti | dp - chilli powder',
  'மிளகாய் பொடி (CATCH)': 'milakaay poti (CATCH) | dp - chilli powder (catch)',
  'மிளகாய் பொடி (NEW)': 'milakaay poti (NEW) | dp - chilli powder (new)',
  'மிளகு': 'milaku | pepper',
  'மிளகு பொடி': 'milaku poti | dp - pepper powder',
  'மிளகு, சீரகப் பொடி': 'milaku, seerakap poti | dp - pepper,jeera powder',
  'மீல் மேக்கர்': 'meel maekkar | mealmaker',
  'முடக்கத்தான் கீரை': 'mutakkaththaan keerai | mudakathan keerai',
  'முட்டைக்கோஸ்': 'muttaikkoas | cabbage',
  'முதல் தர முந்திரி': 'muthal thara munthiri | cashew first quality',
  'முந்திரி': 'munthiri | cashew',
  'முருங்கைக்காய்': 'murungkaikkaay | drumstick',
  'முருங்கைக்கீரை': 'murungkaikkeerai | drumstick leaf',
  'முள்ளங்கி': 'mullangki | radish',
  'முழு கரம் மசாலா': 'muzhu karam masaalaa | dp - whole garam masala',
  'மெட்ராஸ் கரி பொடி': 'metraas kari poti | dp - madras curry powder',
  'மேகி க்யூப்ஸ்': 'maeki kyoops | maagi cubes',
  'மைதா மாவு': 'maithaa maavu | dp - maida ma',
  'ரசப் பொடி': 'rasap poti | dp - rasa powder',
  'ரசமலாய்': 'rasamalaay | rasmalai',
  'ரவை மிக்ஸ்': 'ravai miks | rava mix',
  'ரஸ்க் பொடி': 'rask poti | dp - rusk powder',
  'ரெடிமேட் பூரி': 'retimaet poori | readymade poori',
  'ரோஸ் எசன்ஸ்': 'roas esans | rose essence',
  'லயன் பேரீச்சம் பழ சிரப்': 'layan paereessam pazha sirap | lion date syrup',
  'லிஜ்ஜத் பாப்பட்': 'lijjath paappat | lijjat pappad',
  'லெட்ச கெட்ட கீரை': 'letsa ketta keerai | letcha ketta keerai',
  'லெவிஸ்டா காபி பொடி': 'levistaa kaapi poti | levista coffee powder',
  'வதக்கிய எடை': 'vathakkiya etai | vathakkiya weight',
  'வத்தல் - மோர் மிளகாய்': 'vaththal - moar milakaay | vathal - mor milagaai',
  'வத்தல் அப்பளப் பூ': 'vaththal appalap poo | vathal appala poo',
  'வத்தல் அரிசி': 'vaththal arisi | vathal arisi',
  'வத்தல் அவரை': 'vaththal avarai | vathal avarai',
  'வத்தல் இதயம்': 'vaththal ithayam | vathal heart',
  'வத்தல் உளுந்து': 'vaththal ulunthu | vathal ulundhu',
  'வத்தல் ஓமப்பொடி வடம்': 'vaththal oamappoti vatam | vathal omapodi vadam',
  'வத்தல் கத்தரிக்காய்': 'vaththal kaththarikkaay | vathal brinjal',
  'வத்தல் கார்ன் ஃப்ளேக்ஸ்': 'vaththal kaarn plaeks | vathal corn flakes',
  'வத்தல் கூழ்': 'vaththal koozh | vathal koozh',
  'வத்தல் கொத்தவரங்காய்': 'vaththal koththavarangkaay | vathal kothavarangaai',
  'வத்தல் சீனீஸ் போர்டர்': 'vaththal seenees poartar | vathal chinese border',
  'வத்தல் சீரியல் ரவுண்ட்': 'vaththal seeriyal ravunt | vathal serial round',
  'வத்தல் சுண்டைக்காய்': 'vaththal suntaikkaay | vathal sundakaai',
  'வத்தல் ஜவ்வரிசி நாணயம்': 'vaththal javvarisi naanayam | vathal javurisi coin',
  'வத்தல் டைமண்ட்': 'vaththal taimant | vathal diamond',
  'வத்தல் நிலா': 'vaththal nilaa | vathal nila',
  'வத்தல் நீட்டு': 'vaththal neettu | vathal neetu',
  'வத்தல் பானி பூரி': 'vaththal paani poori | vathal paani poodi',
  'வத்தல் பூண்டு': 'vaththal poontu | vathal garlic | vathal poondu',
  'வத்தல் பேட்': 'vaththal paet | vathal bat',
  'வத்தல் மாவத்தல்': 'vaththal maavaththal | vathal maa vathal',
  'வத்தல் மிளகாய்': 'vaththal milakaay | vathal milagaai',
  'வத்தல் முக்கோணம்': 'vaththal mukkoanam | vathal triangle',
  'வத்தல் முறுக்கு': 'vaththal murukku | vathal murukku',
  'வத்தல் வெங்காயம்': 'vaththal vengkaayam | vathal vengayam',
  'வத்தல் வெள்ளை சூர்யா': 'vaththal vellai sooryaa | vathal vellai surya',
  'வத்தல் வெள்ளை ரிங்': 'vaththal vellai ring | vathal white ring',
  'வரகு': 'varaku | varagu',
  'வறுத்த கொண்டைக்கடலை': 'varuththa kontaikkatalai | roasted chick peas',
  'வறுத்த சீரகப் பொடி': 'varuththa seerakap poti | dp - roasted cumin powder',
  'வறுத்த பாம்பினோ சேமியா': 'varuththa paampinoa saemiyaa | roasted bambino semiya',
  'வறுத்த மிளகு பொடி': 'varuththa milaku poti | dp - roasted pepper powder',
  'வறுத்த வெள்ளை எள்': 'varuththa vellai el | dp - fried white sesame',
  'வறுத்த வேர்க்கடலை': 'varuththa vaerkkatalai | roasted peanut',
  'வறுத்து அரைத்த கோதுமை மாவு': 'varuththu araiththa koathumai maavu | varuthu araitha wheat ma',
  'வாழை இலை': 'vaazhai ilai | plantain leaf',
  'வாழைக்காய்': 'vaazhaikkaay | raw banana',
  'வாழைத்தண்டு': 'vaazhaiththantu | banana stem',
  'வாழைப்பட்டை': 'vaazhaippattai | vazhai pattai',
  'வாழைப்பழம்': 'vaazhaippazham | banana fruit',
  'வாழைப்பூ': 'vaazhaippoo | vazhaipoo',
  'வினிகர்': 'vinikar | vinegar',
  'விரலி மஞ்சள்': 'virali manjsal | virali manjal',
  'வெங்காய ஃப்ளேக்ஸ்': 'vengkaaya plaeks | flakes- onion',
  'வெங்காய வத்தல்': 'vengkaaya vaththal | onion vathal',
  'வெங்காய விதை': 'vengkaaya vithai | onion seeds',
  'வெங்காயப் பொடி': 'vengkaayap poti | dp - onion powder',
  'வெங்காயம்': 'vengkaayam | onion',
  'வெண்டைக்காய்': 'ventaikkaay | lady\'s finger',
  'வெந்தய இலை': 'venthaya ilai | methi leaf',
  'வெந்தயம்': 'venthayam | vendhayam',
  'வெனிலா எசன்ஸ்': 'venilaa esans | vennilla essence',
  'வெள்ளரி விதை': 'vellari vithai | cucumber seed | vellari vedhai',
  'வெள்ளரிக்காய்': 'vellarikkaay | cucumber',
  'வெள்ளை எள்': 'vellai el | white ellu',
  'வெள்ளை கவுனி அரிசி': 'vellai kavuni arisi | vellai kavuni arsi',
  'வெள்ளை சோளம்': 'vellai soalam | white cholam',
  'வெள்ளை பட்டாணி': 'vellai pattaani | white peas',
  'வெள்ளை மிளகு': 'vellai milaku | white pepper',
  'வேப்பம்பூ': 'vaeppampoo | neem flower',
  'வேர்க்கடலை': 'vaerkkatalai | ground nut',
  'ஸ்டார்டர் - சீசி கார்ன் நகெட்ஸ்': 'staartar - seesi kaarn nakets | starter - cheesy corn nuggets',
  'ஸ்பிரிங் ஆனியன் பச்சை பகுதி': 'spiring aaniyan passai pakuthi | spring onion green',
  'ஸ்பிரிங் ஆனியன் வெள்ளை பகுதி': 'spiring aaniyan vellai pakuthi | spring onion white',
  'ஹட்சன் தயிர்': 'hatsan thayir | hatsun curd',
  'ஹட்சன் தயிர் பெட்டி': 'hatsan thayir petti | hatsun curd box',
};

export const INGREDIENT_PHONETIC = {
  'அகத்திக்கீரை': 'akaththikkeerai',
  'அச்சு வெல்லம்': 'assu vellam',
  'அஜினோமோட்டோ': 'ajinoamoattoa',
  'அத்திப்பழம்': 'aththippazham',
  'அனில் திணை சேமியா': 'anil thinai saemiyaa',
  'அனில் வரகு சேமியா': 'anil varaku saemiyaa',
  'அன்னாசிப் பூ': 'annaasip poo',
  'அன்னாசிப்பழம்': 'annaasippazham',
  'அப்பா தட்டு': 'appaa thattu',
  'அமுல் உப்பு இல்லாத வெண்ணெய்': 'amul uppu illaatha venney',
  'அமுல் சீஸ்': 'amul sees',
  'அமுல் மஞ்சள் வெண்ணெய்': 'amul manjsal venney',
  'அமுல் மில்க்மெய்ட்': 'amul milkmeyt',
  'அமெரிக்கன் சீசனிங் பொடி': 'amerikkan seesaning poti',
  'அரிசி - IR 20': 'arisi - IR 20',
  'அரிசி - இட்லி அரிசி (IR 20)': 'arisi - itli arisi (IR 20)',
  'அரிசி - கவுனி': 'arisi - kavuni',
  'அரிசி - குறுவை': 'arisi - kuruvai',
  'அரிசி - சீரக சம்பா': 'arisi - seeraka sampaa',
  'அரிசி - டிபன் அரிசி': 'arisi - tipan arisi',
  'அரிசி - பணியார அரிசி': 'arisi - paniyaara arisi',
  'அரிசி - பாஸ்மதி': 'arisi - paasmathi',
  'அரிசி - பொன்னி பச்சரிசி': 'arisi - ponni passarisi',
  'அரிசி - பொன்னி புழுங்கல்': 'arisi - ponni puzhungkal',
  'அரிசி உப்புமா மாவு': 'arisi uppumaa maavu',
  'அரைக்கீரை': 'araikkeerai',
  'அவரைக்காய்': 'avaraikkaay',
  'அவல்': 'aval',
  'ஆச்சி மசாலா கோபி 65': 'aassi masaalaa koapi 65',
  'ஆந்திரா சாம்பார் காரம்': 'aanthiraa saampaar kaaram',
  'ஆப்பிள்': 'aappil',
  'ஆப்பிள் சைடர் வினிகர்': 'aappil saitar vinikar',
  'ஆம்சூர் பொடி': 'aamsoor poti',
  'ஆவின் தயிர்': 'aavin thayir',
  'ஆவின் பால் பொடி': 'aavin paal poti',
  'இஞ்சி': 'injsi',
  'இஞ்சி பொடி': 'injsi poti',
  'இடியாப்ப மாவு': 'itiyaappa maavu',
  'இட்லி பொடி': 'itli poti',
  'இத்தாலிய மூலிகைகள்': 'iththaaliya moolikaikal',
  'இனிப்பு சோம்பு': 'inippu soampu',
  'இனிப்பு சோளம்': 'inippu soalam',
  'இலை - வட்ட இலை': 'ilai - vatta ilai',
  'இளநீர்': 'ilaneer',
  'ஈனோ உப்பு': 'eenoa uppu',
  'ஈஸ்ட்': 'eest',
  'உஜாலா கத்தரிக்காய்': 'ujaalaa kaththarikkaay',
  'உருளைக்கிழங்கு (மேட்டுப்பாளையம்)': 'urulaikkizhangku (maettuppaalaiyam)',
  'உருளைக்கிழங்கு சிப்ஸ்': 'urulaikkizhangku sips',
  'உருளைக்கிழங்கு ஸ்டார்ச்': 'urulaikkizhangku staars',
  'உறைந்த பட்டாணி': 'uraintha pattaani',
  'உலர் சோயா பீன்ஸ்': 'ular soayaa peens',
  'உலர் டபுள் பீன்ஸ்': 'ular tapul peens',
  'உலர் பச்சைப் பட்டாணி': 'ular passaip pattaani',
  'உலர் பட்டர் பீன்ஸ்': 'ular pattar peens',
  'உலர் பட்டாணி': 'ular pattaani',
  'ஊதா முட்டைக்கோஸ்': 'oothaa muttaikkoas',
  'ஊறுகாய் - இஞ்சி தொக்கு': 'oorukaay - injsi thokku',
  'ஊறுகாய் - இஞ்சி புளி': 'oorukaay - injsi puli',
  'ஊறுகாய் - பூண்டு ஊறுகாய்': 'oorukaay - poontu oorukaay',
  'ஊறுகாய் - வெங்காய தொக்கு': 'oorukaay - vengkaaya thokku',
  'எண்ணெய் - GN நல்லெண்ணெய்': 'enney - GN nallenney',
  'எண்ணெய் - எண்ணெய்': 'enney - enney',
  'எண்ணெய் - கடுகு எண்ணெய்': 'enney - katuku enney',
  'எண்ணெய் - தேங்காய் எண்ணெய்': 'enney - thaengkaay enney',
  'எண்ணெய் - நல்லெண்ணெய்': 'enney - nallenney',
  'எலுமிச்சை': 'elumissai',
  'எள் பொடி': 'el poti',
  'ஏடு': 'aetu',
  'ஏலக்காய்': 'aelakkaay',
  'ஏலக்காய் பொடி': 'aelakkaay poti',
  'ஏலக்கி வாழைப்பழம்': 'aelakki vaazhaippazham',
  'ஓட்ஸ்': 'oats',
  'ஓமப்பொடி': 'oamappoti',
  'ஓமம்': 'oamam',
  'ஓரிகானோ': 'oarikaanoa',
  'கசகசா': 'kasakasaa',
  'கசூரி மேத்தி': 'kasoori maeththi',
  'கடலை மாவு': 'katalai maavu',
  'கடுகு': 'katuku',
  'கடை ஆவக்காய் மாங்காய் ஊறுகாய்': 'katai aavakkaay maangkaay oorukaay',
  'கடை எலுமிச்சை ஊறுகாய்': 'katai elumissai oorukaay',
  'கடை கலவை காய்கறி ஊறுகாய்': 'katai kalavai kaaykari oorukaay',
  'கடை கொங்குரா ஊறுகாய்': 'katai kongkuraa oorukaay',
  'கடை கொடாரங்காய் ஊறுகாய்': 'katai kotaarangkaay oorukaay',
  'கடை புளிச்ச கீரை தொக்கு': 'katai pulissa keerai thokku',
  'கடை மாங்காய் தொக்கு': 'katai maangkaay thokku',
  'கடை வடுமாங்காய் ஊறுகாய்': 'katai vatumaangkaay oorukaay',
  'கம்பு': 'kampu',
  'கரம் மசாலா': 'karam masaalaa',
  'கருஞ்சீரகம்': 'karunjseerakam',
  'கருணைக்கிழங்கு': 'karunaikkizhangku',
  'கருப்பட்டி': 'karuppatti',
  'கருப்பட்டி காஜு கட்லி': 'karuppatti kaaju katli',
  'கருப்பு உப்பு': 'karuppu uppu',
  'கருப்பு எள்': 'karuppu el',
  'கருப்பு ஏலக்காய்': 'karuppu aelakkaay',
  'கருவேப்பிலை': 'karuvaeppilai',
  'கற்கண்டு': 'karkantu',
  'கலா கோஸ்': 'kalaa koas',
  'கல் உப்பு': 'kal uppu',
  'கல் பாசி': 'kal paasi',
  'கஸ்டர்ட் பொடி': 'kastart poti',
  'காபி பொடி': 'kaapi poti',
  'காராமணி': 'kaaraamani',
  'கார்ன் ஃப்ளேக்ஸ்': 'kaarn plaeks',
  'கார்ன் ஃப்ளோர்': 'kaarn ploar',
  'காலிஃபிளவர்': 'kaalipilavar',
  'காளான்': 'kaalaan',
  'காஷ்மீரி மிளகாய் பொடி': 'kaashmeeri milakaay poti',
  'கிராம்பு': 'kiraampu',
  'கிஸ்மிஸ்': 'kismis',
  'கீரை': 'keerai',
  'குங்குமப்பூ': 'kungkumappoo',
  'குடிக்கும் சாக்லேட்': 'kutikkum saaklaet',
  'குடைமிளகாய்': 'kutaimilakaay',
  'குட்டி உருளைக்கிழங்கு': 'kutti urulaikkizhangku',
  'குட்டி கத்தரிக்காய்': 'kutti kaththarikkaay',
  'கும்மாய மாவு': 'kummaaya maavu',
  'குறு மிளகு': 'kuru milaku',
  'குறுவை அரிசி மாவு': 'kuruvai arisi maavu',
  'குல்கந்த்': 'kulkanth',
  'கேசரி பொடி': 'kaesari poti',
  'கேப்பை மாவு': 'kaeppai maavu',
  'கேரட்': 'kaerat',
  'கேழ்வரகு': 'kaezhvaraku',
  'கேழ்வரகு மாவு': 'kaezhvaraku maavu',
  'கையுறை': 'kaiyurai',
  'கொதித்த சீரக எடை': 'kothiththa seeraka etai',
  'கொத்தமல்லி': 'koththamalli',
  'கொத்தமல்லி இலை': 'koththamalli ilai',
  'கொத்தவரங்காய்': 'koththavarangkaay',
  'கொள்ளு': 'kollu',
  'கோக்கோ பொடி': 'koakkoa poti',
  'கோதாஸ் காபி பொடி': 'koathaas kaapi poti',
  'கோதுமை': 'koathumai',
  'கோதுமை தலியா': 'koathumai thaliyaa',
  'கோதுமை பாஸ்தா': 'koathumai paasthaa',
  'கோதுமை மாவு': 'koathumai maavu',
  'கோதுமை ரவை': 'koathumai ravai',
  'கோபி வறுவல் மாவு': 'koapi varuval maavu',
  'கோவா (இனிப்பு இல்லாதது)': 'koavaa (inippu illaathathu)',
  'கோவைக்காய்': 'koavaikkaay',
  'கோஸ்மல்லி கத்தரிக்காய்': 'koasmalli kaththarikkaay',
  'சக்கர வரட்டி': 'sakkara varatti',
  'சக்கரைவள்ளி': 'sakkaraivalli',
  'சக்கரைவள்ளிக் கிழங்கு': 'sakkaraivallik kizhangku',
  'சம்பா கோதுமை': 'sampaa koathumai',
  'சர்க்கரை': 'sarkkarai',
  'சர்க்கரை பொடி': 'sarkkarai poti',
  'சாட் மசாலா': 'saat masaalaa',
  'சாப்பாட்டு இலை': 'saappaattu ilai',
  'சாம்பார் டாப்பிங் பொடி': 'saampaar taapping poti',
  'சாம்பார் பொடி': 'saampaar poti',
  'சாஸ் - இனிப்பு மிளகாய் சாஸ்': 'saas - inippu milakaay saas',
  'சாஸ் - சிவப்பு மிளகாய் சாஸ்': 'saas - sivappu milakaay saas',
  'சாஸ் - செஷ்வான் சாஸ்': 'saas - seshvaan saas',
  'சாஸ் - சோயா சாஸ்': 'saas - soayaa saas',
  'சாஸ் - தக்காளி சாஸ்': 'saas - thakkaali saas',
  'சாஸ் - பாஸ்தா சாஸ்': 'saas - paasthaa saas',
  'சாஸ் - பூண்டு சாஸ்': 'saas - poontu saas',
  'சாஸ் - மயோனெய்ஸ் சாஸ்': 'saas - mayoaneys saas',
  'சாஸ் - மிளகாய் சாஸ்': 'saas - milakaay saas',
  'சாஸ் - மோமோஸ் சாஸ்': 'saas - moamoas saas',
  'சாஸ் - வெள்ளை சாஸ்': 'saas - vellai saas',
  'சிங் மசாலா': 'sing masaalaa',
  'சின்ன சோள மாவு': 'sinna soala maavu',
  'சின்ன வெங்காயம்': 'sinna vengkaayam',
  'சிப்ஸ் உருளைக்கிழங்கு': 'sips urulaikkizhangku',
  'சிறிய அப்பளம்': 'siriya appalam',
  'சிறுதானியம் - குதிரைவாலி': 'siruthaaniyam - kuthiraivaali',
  'சிறுதானியம் - கேப்பை': 'siruthaaniyam - kaeppai',
  'சிறுதானியம் - சாமை': 'siruthaaniyam - saamai',
  'சிறுதானியம் - திணை': 'siruthaaniyam - thinai',
  'சிறுதானியம் - வரகு': 'siruthaaniyam - varaku',
  'சிவப்பு அவல்': 'sivappu aval',
  'சிவப்பு குடைமிளகாய்': 'sivappu kutaimilakaay',
  'சிவப்பு பூசணிக்காய்': 'sivappu poosanikkaay',
  'சிவப்பு மிளகாய் பூண்டு வினிகர்': 'sivappu milakaay poontu vinikar',
  'சீசி கார்ன் நகெட்ஸ்': 'seesi kaarn nakets',
  'சீரகப் பொடி': 'seerakap poti',
  'சீரகம்': 'seerakam',
  'சுக்கு': 'sukku',
  'சுக்கு மல்லி': 'sukku malli',
  'சுண்டைக்காய்': 'suntaikkaay',
  'சுபல் கத்தரிக்காய்': 'supal kaththarikkaay',
  'சுரைக்காய்': 'suraikkaay',
  'செர்ரி': 'serri',
  'செலரி உப்பு': 'selari uppu',
  'செஷ்வான் சட்னி (ரிதா அரோரா)': 'seshvaan satni (rithaa aroaraa)',
  'சேனைக்கிழங்கு': 'saenaikkizhangku',
  'சேப்பங்கிழங்கு': 'saeppangkizhangku',
  'சைனா கிராஸ்': 'sainaa kiraas',
  'சோம்பு': 'soampu',
  'சோம்பு பொடி': 'soampu poti',
  'சோயா சங்': 'soayaa sang',
  'சோயா பீன்ஸ்': 'soayaa peens',
  'சோயா மாவு': 'soayaa maavu',
  'சோள மாவு': 'soala maavu',
  'சோள ரவை': 'soala ravai',
  'சௌ சௌ': 'sau sau',
  'ஜல் ஜீரா': 'jal jeeraa',
  'ஜாதிக்காய்': 'jaathikkaay',
  'ஜாதிக்காய் பொடி': 'jaathikkaay poti',
  'ஜாதிப்பத்திரி': 'jaathippaththiri',
  'ஜாதிப்பத்திரி பொடி': 'jaathippaththiri poti',
  'ஜாம்': 'jaam',
  'டாங்': 'taang',
  'டாடா உப்பு': 'taataa uppu',
  'டிபன் தட்டு இலை': 'tipan thattu ilai',
  'டூட்டி ஃப்ரூட்டி': 'tootti prootti',
  'டைமண்ட் கற்கண்டு': 'taimant karkantu',
  'ட்ரூ சேமியா': 'troo saemiyaa',
  'தக்காளி (நறுக்கியது)': 'thakkaali (narukkiyathu)',
  'தக்காளி கெட்சப்': 'thakkaali ketsap',
  'தக்காளி தொக்கு': 'thakkaali thokku',
  'தக்காளி பேஸ்ட்': 'thakkaali paest',
  'தட்டை அவரைக்காய்': 'thattai avaraikkaay',
  'தட்டைப்பயத்தங்காய்': 'thattaippayaththangkaay',
  'தனியா': 'thaniyaa',
  'தனியா பொடி': 'thaniyaa poti',
  'தயிர்': 'thayir',
  'தர்பூசணி விதை': 'tharpoosani vithai',
  'தாளிப்பு வடகம்': 'thaalippu vatakam',
  'தேங்காய்': 'thaengkaay',
  'தேங்காய் கிரீம்': 'thaengkaay kireem',
  'தேங்காய் பால்': 'thaengkaay paal',
  'தேநீர்': 'thaeneer',
  'தேன்': 'thaen',
  'நவீன் நறுக்கிய தக்காளி': 'naveen narukkiya thakkaali',
  'நாட்டு சர்க்கரை': 'naattu sarkkarai',
  'நியூட்ரியண்ட் மாவு': 'niyootriyant maavu',
  'நிலவேம்பு': 'nilavaempu',
  'நீளமான புடலங்காய்': 'neelamaana putalangkaay',
  'நூடுல்ஸ் - சீன நூடுல்ஸ்': 'nootuls - seena nootuls',
  'நூடுல்ஸ் - மேகி நூடுல்ஸ்': 'nootuls - maeki nootuls',
  'நூல்கோல்': 'noolkoal',
  'நெய்': 'ney',
  'பசலைக்கீரை': 'pasalaikkeerai',
  'பச்சரிசி மாவு': 'passarisi maavu',
  'பச்சை சுக்கினி': 'passai sukkini',
  'பச்சை டபுள் பீன்ஸ்': 'passai tapul peens',
  'பச்சை பலாக்காய்': 'passai palaakkaay',
  'பச்சை மாங்காய்': 'passai maangkaay',
  'பச்சை மிளகாய்': 'passai milakaay',
  'பச்சை மொச்சை': 'passai mossai',
  'பச்சை வேர்க்கடலை': 'passai vaerkkatalai',
  'பச்சைப் பட்டாணி': 'passaip pattaani',
  'பஜா மசாலா': 'pajaa masaalaa',
  'பஜ்ஜி மிளகாய்': 'pajji milakaay',
  'பட்டர் பீன்ஸ்': 'pattar peens',
  'பட்டை': 'pattai',
  'பனீர்': 'paneer',
  'பனீர் திராட்சை': 'paneer thiraatsai',
  'பனை கற்கண்டு': 'panai karkantu',
  'பருப்பு - இட்லிக்கான உளுந்து': 'paruppu - itlikkaana ulunthu',
  'பருப்பு - உளுந்து': 'paruppu - ulunthu',
  'பருப்பு - கடலைப் பருப்பு': 'paruppu - katalaip paruppu',
  'பருப்பு - கருப்பு உளுந்து': 'paruppu - karuppu ulunthu',
  'பருப்பு - கருப்பு கொண்டைக்கடலை': 'paruppu - karuppu kontaikkatalai',
  'பருப்பு - சிறிய வெள்ளை கொண்டைக்கடலை': 'paruppu - siriya vellai kontaikkatalai',
  'பருப்பு - சிவப்பு தட்டைப்பயறு': 'paruppu - sivappu thattaippayaru',
  'பருப்பு - தாளிப்புக்கான உளுந்து': 'paruppu - thaalippukkaana ulunthu',
  'பருப்பு - துவரம் பருப்பு': 'paruppu - thuvaram paruppu',
  'பருப்பு - பட்டாணி பருப்பு': 'paruppu - pattaani paruppu',
  'பருப்பு - பாசிப்பயறு': 'paruppu - paasippayaru',
  'பருப்பு - பாசிப்பருப்பு': 'paruppu - paasipparuppu',
  'பருப்பு - பொட்டுக்கடலை': 'paruppu - pottukkatalai',
  'பருப்பு - மசூர் பருப்பு': 'paruppu - masoor paruppu',
  'பருப்பு - முளைகட்டிய பாசிப்பயறு': 'paruppu - mulaikattiya paasippayaru',
  'பருப்பு - மொச்சை': 'paruppu - mossai',
  'பருப்பு - ராஜ்மா': 'paruppu - raajmaa',
  'பருப்பு - வெள்ளை கொண்டைக்கடலை': 'paruppu - vellai kontaikkatalai',
  'பருப்பு - வெள்ளை சோயா': 'paruppu - vellai soayaa',
  'பருப்பு - வெள்ளை தட்டைப்பயறு': 'paruppu - vellai thattaippayaru',
  'பருப்புக்கீரை': 'paruppukkeerai',
  'பழம் - மாம்பழம்': 'pazham - maampazham',
  'பழுத்த பச்சை மிளகாய்': 'pazhuththa passai milakaay',
  'பாகற்காய்': 'paakarkaay',
  'பாங்கோ பிரெட் தூள்': 'paangkoa piret thool',
  'பாசுந்தி': 'paasunthi',
  'பாதாம்': 'paathaam',
  'பாதாம் பிசின்': 'paathaam pisin',
  'பாப்படம்': 'paappatam',
  'பாப்ரிகா பொடி': 'paaprikaa poti',
  'பாயாசம் காய்ச்சிய அளவு': 'paayaasam kaayssiya alavu',
  'பாரம்பரிய அரிசி - கருங்குறுவை': 'paarampariya arisi - karungkuruvai',
  'பாரம்பரிய அரிசி - காட்டுயானம்': 'paarampariya arisi - kaattuyaanam',
  'பாரம்பரிய அரிசி - தூயமல்லி அரிசி': 'paarampariya arisi - thooyamalli arisi',
  'பாரம்பரிய அரிசி - நவரா': 'paarampariya arisi - navaraa',
  'பாரம்பரிய அரிசி - பூங்கார்': 'paarampariya arisi - poongkaar',
  'பாரம்பரிய அரிசி - மாப்பிள்ளை சம்பா': 'paarampariya arisi - maappillai sampaa',
  'பாரம்பரிய அரிசி - மூங்கில் அரிசி': 'paarampariya arisi - moongkil arisi',
  'பார்லி': 'paarli',
  'பார்ஸ்லி': 'paarsli',
  'பாலடா': 'paalataa',
  'பால் (பிரவுன் பாக்கெட்)': 'paal (piravun paakket)',
  'பால் - பால்': 'paal - paal',
  'பால் - பால் (ஆரஞ்சு பாக்கெட்)': 'paal - paal (aaranjsu paakket)',
  'பாவ் பன்': 'paav pan',
  'பாஸ்தா - ஃபார்ஃபாலே': 'paasthaa - paarpaalae',
  'பாஸ்தா - ஃபுசில்லி': 'paasthaa - pusilli',
  'பாஸ்தா - மக்கரோனி': 'paasthaa - makkaroani',
  'பிரவுன் சர்க்கரை': 'piravun sarkkarai',
  'பிரியாணி இலை': 'piriyaani ilai',
  'பிரியாணி இலை பொடி': 'piriyaani ilai poti',
  'பிரெட்': 'piret',
  'பிரோக்கோலி': 'piroakkoali',
  'பிலாக்கொட்டை': 'pilaakkottai',
  'பீட்சா சீசனிங் பொடி': 'peetsaa seesaning poti',
  'பீட்ரூட்': 'peetroot',
  'பீன்ஸ்': 'peens',
  'பீர்க்கங்காய்': 'peerkkangkaay',
  'புடலங்காய்': 'putalangkaay',
  'புதினா இலை': 'puthinaa ilai',
  'புதிய கிரீம்': 'puthiya kireem',
  'புளி': 'puli',
  'புளிக் குழம்பு பொடி': 'pulik kuzhampu poti',
  'புஷ் சிவப்பு கலர்': 'push sivappu kalar',
  'பூசணி விதை': 'poosani vithai',
  'பூசணிக்காய்': 'poosanikkaay',
  'பூண்டு': 'poontu',
  'பூண்டு ஃப்ளேக்ஸ்': 'poontu plaeks',
  'பூண்டு பொடி ஊறுகாய்': 'poontu poti oorukaay',
  'பெங்களூர் புளி': 'pengkaloor puli',
  'பெரிய அப்பளம்': 'periya appalam',
  'பெரிய ரவை': 'periya ravai',
  'பெருங்காயம்': 'perungkaayam',
  'பேக்கிங் சோடா': 'paekking soataa',
  'பேக்கிங் பவுடர்': 'paekking pavutar',
  'பேசில்': 'paesil',
  'பேபி கார்ன்': 'paepi kaarn',
  'பேபி கார்ன் பெட்டி': 'paepi kaarn petti',
  'பேபி கார்ன், காளான் வறுவல் மாவு': 'paepi kaarn, kaalaan varuval maavu',
  'பேரீச்சம் பழம்': 'paereessam pazham',
  'பொடியாக நறுக்கிய பூண்டு': 'potiyaaka narukkiya poontu',
  'பொட்டுக்கடலை': 'pottukkatalai',
  'பொன்னாங்கண்ணி கீரை': 'ponnaangkanni keerai',
  'பொரி': 'pori',
  'பொரித்த பகோடா': 'poriththa pakoataa',
  'பொரியல் பொடி': 'poriyal poti',
  'போர்ன்விட்டா': 'poarnvittaa',
  'மக்காச்சோளம்': 'makkaassoalam',
  'மசாலா பால் பொடி': 'masaalaa paal poti',
  'மஞ்சள் குடைமிளகாய்': 'manjsal kutaimilakaay',
  'மஞ்சள் சுக்கினி': 'manjsal sukkini',
  'மஞ்சள் பொடி': 'manjsal poti',
  'மஞ்சூரியன் மாவு': 'manjsooriyan maavu',
  'மணத்தக்காளி': 'manaththakkaali',
  'மணத்தக்காளி கீரை': 'manaththakkaali keerai',
  'மண்டா வெல்லம்': 'mantaa vellam',
  'மயோனெய்ஸ்': 'mayoaneys',
  'மரவள்ளிக்கிழங்கு': 'maravallikkizhangku',
  'மாங்காய் இஞ்சி': 'maangkaay injsi',
  'மாதுளம்பழம்': 'maathulampazham',
  'மாதுளை பொடி': 'maathulai poti',
  'மாதுளை விதை பொடி': 'maathulai vithai poti',
  'மாவு ஜவ்வரிசி': 'maavu javvarisi',
  'மாஸ் பாதாம் மிக்ஸ்': 'maas paathaam miks',
  'மில்கி மிஸ்ட் பனீர்': 'milki mist paneer',
  'மிளகாய் - சம்பா மிளகாய்': 'milakaay - sampaa milakaay',
  'மிளகாய் - சிவப்பு மிளகாய்': 'milakaay - sivappu milakaay',
  'மிளகாய் - சிவப்பு மிளகாய் (புதியது)': 'milakaay - sivappu milakaay (puthiyathu)',
  'மிளகாய் - வட இந்திய மிளகாய்': 'milakaay - vata inthiya milakaay',
  'மிளகாய் பொடி': 'milakaay poti',
  'மிளகாய் பொடி (CATCH)': 'milakaay poti (CATCH)',
  'மிளகாய் பொடி (NEW)': 'milakaay poti (NEW)',
  'மிளகு': 'milaku',
  'மிளகு பொடி': 'milaku poti',
  'மிளகு, சீரகப் பொடி': 'milaku, seerakap poti',
  'மீல் மேக்கர்': 'meel maekkar',
  'முடக்கத்தான் கீரை': 'mutakkaththaan keerai',
  'முட்டைக்கோஸ்': 'muttaikkoas',
  'முதல் தர முந்திரி': 'muthal thara munthiri',
  'முந்திரி': 'munthiri',
  'முருங்கைக்காய்': 'murungkaikkaay',
  'முருங்கைக்கீரை': 'murungkaikkeerai',
  'முள்ளங்கி': 'mullangki',
  'முழு கரம் மசாலா': 'muzhu karam masaalaa',
  'மெட்ராஸ் கரி பொடி': 'metraas kari poti',
  'மேகி க்யூப்ஸ்': 'maeki kyoops',
  'மைதா மாவு': 'maithaa maavu',
  'ரசப் பொடி': 'rasap poti',
  'ரசமலாய்': 'rasamalaay',
  'ரவை மிக்ஸ்': 'ravai miks',
  'ரஸ்க் பொடி': 'rask poti',
  'ரெடிமேட் பூரி': 'retimaet poori',
  'ரோஸ் எசன்ஸ்': 'roas esans',
  'லயன் பேரீச்சம் பழ சிரப்': 'layan paereessam pazha sirap',
  'லிஜ்ஜத் பாப்பட்': 'lijjath paappat',
  'லெட்ச கெட்ட கீரை': 'letsa ketta keerai',
  'லெவிஸ்டா காபி பொடி': 'levistaa kaapi poti',
  'வதக்கிய எடை': 'vathakkiya etai',
  'வத்தல் - மோர் மிளகாய்': 'vaththal - moar milakaay',
  'வத்தல் அப்பளப் பூ': 'vaththal appalap poo',
  'வத்தல் அரிசி': 'vaththal arisi',
  'வத்தல் அவரை': 'vaththal avarai',
  'வத்தல் இதயம்': 'vaththal ithayam',
  'வத்தல் உளுந்து': 'vaththal ulunthu',
  'வத்தல் ஓமப்பொடி வடம்': 'vaththal oamappoti vatam',
  'வத்தல் கத்தரிக்காய்': 'vaththal kaththarikkaay',
  'வத்தல் கார்ன் ஃப்ளேக்ஸ்': 'vaththal kaarn plaeks',
  'வத்தல் கூழ்': 'vaththal koozh',
  'வத்தல் கொத்தவரங்காய்': 'vaththal koththavarangkaay',
  'வத்தல் சீனீஸ் போர்டர்': 'vaththal seenees poartar',
  'வத்தல் சீரியல் ரவுண்ட்': 'vaththal seeriyal ravunt',
  'வத்தல் சுண்டைக்காய்': 'vaththal suntaikkaay',
  'வத்தல் ஜவ்வரிசி நாணயம்': 'vaththal javvarisi naanayam',
  'வத்தல் டைமண்ட்': 'vaththal taimant',
  'வத்தல் நிலா': 'vaththal nilaa',
  'வத்தல் நீட்டு': 'vaththal neettu',
  'வத்தல் பானி பூரி': 'vaththal paani poori',
  'வத்தல் பூண்டு': 'vaththal poontu',
  'வத்தல் பேட்': 'vaththal paet',
  'வத்தல் மாவத்தல்': 'vaththal maavaththal',
  'வத்தல் மிளகாய்': 'vaththal milakaay',
  'வத்தல் முக்கோணம்': 'vaththal mukkoanam',
  'வத்தல் முறுக்கு': 'vaththal murukku',
  'வத்தல் வெங்காயம்': 'vaththal vengkaayam',
  'வத்தல் வெள்ளை சூர்யா': 'vaththal vellai sooryaa',
  'வத்தல் வெள்ளை ரிங்': 'vaththal vellai ring',
  'வரகு': 'varaku',
  'வறுத்த கொண்டைக்கடலை': 'varuththa kontaikkatalai',
  'வறுத்த சீரகப் பொடி': 'varuththa seerakap poti',
  'வறுத்த பாம்பினோ சேமியா': 'varuththa paampinoa saemiyaa',
  'வறுத்த மிளகு பொடி': 'varuththa milaku poti',
  'வறுத்த வெள்ளை எள்': 'varuththa vellai el',
  'வறுத்த வேர்க்கடலை': 'varuththa vaerkkatalai',
  'வறுத்து அரைத்த கோதுமை மாவு': 'varuththu araiththa koathumai maavu',
  'வாழை இலை': 'vaazhai ilai',
  'வாழைக்காய்': 'vaazhaikkaay',
  'வாழைத்தண்டு': 'vaazhaiththantu',
  'வாழைப்பட்டை': 'vaazhaippattai',
  'வாழைப்பழம்': 'vaazhaippazham',
  'வாழைப்பூ': 'vaazhaippoo',
  'வினிகர்': 'vinikar',
  'விரலி மஞ்சள்': 'virali manjsal',
  'வெங்காய ஃப்ளேக்ஸ்': 'vengkaaya plaeks',
  'வெங்காய வத்தல்': 'vengkaaya vaththal',
  'வெங்காய விதை': 'vengkaaya vithai',
  'வெங்காயப் பொடி': 'vengkaayap poti',
  'வெங்காயம்': 'vengkaayam',
  'வெண்டைக்காய்': 'ventaikkaay',
  'வெந்தய இலை': 'venthaya ilai',
  'வெந்தயம்': 'venthayam',
  'வெனிலா எசன்ஸ்': 'venilaa esans',
  'வெள்ளரி விதை': 'vellari vithai',
  'வெள்ளரிக்காய்': 'vellarikkaay',
  'வெள்ளை எள்': 'vellai el',
  'வெள்ளை கவுனி அரிசி': 'vellai kavuni arisi',
  'வெள்ளை சோளம்': 'vellai soalam',
  'வெள்ளை பட்டாணி': 'vellai pattaani',
  'வெள்ளை மிளகு': 'vellai milaku',
  'வேப்பம்பூ': 'vaeppampoo',
  'வேர்க்கடலை': 'vaerkkatalai',
  'ஸ்டார்டர் - சீசி கார்ன் நகெட்ஸ்': 'staartar - seesi kaarn nakets',
  'ஸ்பிரிங் ஆனியன் பச்சை பகுதி': 'spiring aaniyan passai pakuthi',
  'ஸ்பிரிங் ஆனியன் வெள்ளை பகுதி': 'spiring aaniyan vellai pakuthi',
  'ஹட்சன் தயிர்': 'hatsan thayir',
  'ஹட்சன் தயிர் பெட்டி': 'hatsan thayir petti',
};
