// Auto-generated from kal_vegetable_list.xlsx — Tamil-only ingredient master.
// 117 vegetables + 343 grocery = 460 items. Latin prefixes (DP/G/KTR) stripped,
// duplicate Tamil names merged, sorted in Tamil alphabetical order.
// Re-importing skips any name that already exists.
export const SEED_INGREDIENTS = [
  { name: 'அகத்திக்கீரை', category: 'vegetable', unit: 'g' },
  { name: 'அச்சு வெல்லம்', category: 'grocery', unit: 'kg' },
  { name: 'அஜினோமோட்டோ', category: 'grocery', unit: 'kg' },
  { name: 'அத்திப்பழம்', category: 'grocery', unit: 'g' },
  { name: 'அனில் திணை சேமியா', category: 'grocery', unit: 'kg' },
  { name: 'அனில் வரகு சேமியா', category: 'grocery', unit: 'kg' },
  { name: 'அன்னாசிப் பூ', category: 'grocery', unit: 'kg' },
  { name: 'அன்னாசிப்பழம்', category: 'vegetable', unit: 'kg' },
  { name: 'அப்பா தட்டு', category: 'grocery', unit: 'nos' },
  { name: 'அமுல் உப்பு இல்லாத வெண்ணெய்', category: 'grocery', unit: 'g' },
  { name: 'அமுல் சீஸ்', category: 'grocery', unit: 'kg' },
  { name: 'அமுல் மஞ்சள் வெண்ணெய்', category: 'grocery', unit: 'g' },
  { name: 'அமுல் மில்க்மெய்ட்', category: 'grocery', unit: 'litre' },
  { name: 'அமெரிக்கன் சீசனிங் பொடி', category: 'grocery', unit: 'g' },
  { name: 'அரிசி - IR 20', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - இட்லி அரிசி (IR 20)', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - கவுனி', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - குறுவை', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - சீரக சம்பா', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - டிபன் அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - பணியார அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - பாஸ்மதி', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - பொன்னி பச்சரிசி', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி - பொன்னி புழுங்கல்', category: 'grocery', unit: 'kg' },
  { name: 'அரிசி உப்புமா மாவு', category: 'grocery', unit: 'g' },
  { name: 'அரைக்கீரை', category: 'vegetable', unit: 'g' },
  { name: 'அவரைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'அவல்', category: 'grocery', unit: 'kg' },
  { name: 'ஆச்சி மசாலா கோபி 65', category: 'grocery', unit: 'g' },
  { name: 'ஆந்திரா சாம்பார் காரம்', category: 'grocery', unit: 'kg' },
  { name: 'ஆப்பிள்', category: 'vegetable', unit: 'kg' },
  { name: 'ஆப்பிள் சைடர் வினிகர்', category: 'grocery', unit: 'litre' },
  { name: 'ஆம்சூர் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஆவின் தயிர்', category: 'vegetable', unit: 'litre' },
  { name: 'ஆவின் பால் பொடி', category: 'grocery', unit: 'litre' },
  { name: 'இஞ்சி', category: 'vegetable', unit: 'kg' },
  { name: 'இஞ்சி பொடி', category: 'grocery', unit: 'g' },
  { name: 'இடியாப்ப மாவு', category: 'grocery', unit: 'kg' },
  { name: 'இட்லி பொடி', category: 'grocery', unit: 'g' },
  { name: 'இத்தாலிய மூலிகைகள்', category: 'grocery', unit: 'kg' },
  { name: 'இனிப்பு சோம்பு', category: 'grocery', unit: 'kg' },
  { name: 'இனிப்பு சோளம்', category: 'vegetable', unit: 'kg' },
  { name: 'இலை - வட்ட இலை', category: 'vegetable', unit: 'g' },
  { name: 'இளநீர்', category: 'vegetable', unit: 'kg' },
  { name: 'ஈனோ உப்பு', category: 'grocery', unit: 'g' },
  { name: 'ஈஸ்ட்', category: 'grocery', unit: 'kg' },
  { name: 'உஜாலா கத்தரிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'உருளைக்கிழங்கு (மேட்டுப்பாளையம்)', category: 'vegetable', unit: 'kg' },
  { name: 'உருளைக்கிழங்கு சிப்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'உருளைக்கிழங்கு ஸ்டார்ச்', category: 'grocery', unit: 'g' },
  { name: 'உறைந்த பட்டாணி', category: 'vegetable', unit: 'kg' },
  { name: 'உலர் சோயா பீன்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'உலர் டபுள் பீன்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'உலர் பச்சைப் பட்டாணி', category: 'grocery', unit: 'kg' },
  { name: 'உலர் பட்டர் பீன்ஸ்', category: 'grocery', unit: 'g' },
  { name: 'உலர் பட்டாணி', category: 'grocery', unit: 'kg' },
  { name: 'ஊதா முட்டைக்கோஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'ஊறுகாய் - இஞ்சி தொக்கு', category: 'grocery', unit: 'kg' },
  { name: 'ஊறுகாய் - இஞ்சி புளி', category: 'grocery', unit: 'kg' },
  { name: 'ஊறுகாய் - பூண்டு ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'ஊறுகாய் - வெங்காய தொக்கு', category: 'grocery', unit: 'kg' },
  { name: 'எண்ணெய் - GN நல்லெண்ணெய்', category: 'grocery', unit: 'litre' },
  { name: 'எண்ணெய் - எண்ணெய்', category: 'grocery', unit: 'litre' },
  { name: 'எண்ணெய் - கடுகு எண்ணெய்', category: 'grocery', unit: 'litre' },
  { name: 'எண்ணெய் - தேங்காய் எண்ணெய்', category: 'grocery', unit: 'litre' },
  { name: 'எண்ணெய் - நல்லெண்ணெய்', category: 'grocery', unit: 'litre' },
  { name: 'எலுமிச்சை', category: 'vegetable', unit: 'kg' },
  { name: 'எள் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஏடு', category: 'vegetable', unit: 'kg' },
  { name: 'ஏலக்காய்', category: 'grocery', unit: 'g' },
  { name: 'ஏலக்காய் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஏலக்கி வாழைப்பழம்', category: 'vegetable', unit: 'kg' },
  { name: 'ஓட்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'ஓமப்பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஓமம்', category: 'grocery', unit: 'g' },
  { name: 'ஓரிகானோ', category: 'grocery', unit: 'kg' },
  { name: 'கசகசா', category: 'grocery', unit: 'kg' },
  { name: 'கசூரி மேத்தி', category: 'grocery', unit: 'kg' },
  { name: 'கடலை மாவு', category: 'grocery', unit: 'kg' },
  { name: 'கடுகு', category: 'grocery', unit: 'kg' },
  { name: 'கடை ஆவக்காய் மாங்காய் ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கடை எலுமிச்சை ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கடை கலவை காய்கறி ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கடை கொங்குரா ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கடை கொடாரங்காய் ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கடை புளிச்ச கீரை தொக்கு', category: 'grocery', unit: 'g' },
  { name: 'கடை மாங்காய் தொக்கு', category: 'grocery', unit: 'kg' },
  { name: 'கடை வடுமாங்காய் ஊறுகாய்', category: 'grocery', unit: 'kg' },
  { name: 'கம்பு', category: 'grocery', unit: 'kg' },
  { name: 'கரம் மசாலா', category: 'grocery', unit: 'g' },
  { name: 'கருஞ்சீரகம்', category: 'grocery', unit: 'g' },
  { name: 'கருணைக்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'கருப்பட்டி', category: 'grocery', unit: 'kg' },
  { name: 'கருப்பட்டி காஜு கட்லி', category: 'vegetable', unit: 'kg' },
  { name: 'கருப்பு உப்பு', category: 'grocery', unit: 'g' },
  { name: 'கருப்பு எள்', category: 'grocery', unit: 'g' },
  { name: 'கருப்பு ஏலக்காய்', category: 'grocery', unit: 'g' },
  { name: 'கருவேப்பிலை', category: 'vegetable', unit: 'g' },
  { name: 'கற்கண்டு', category: 'grocery', unit: 'kg' },
  { name: 'கலா கோஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'கல் உப்பு', category: 'grocery', unit: 'g' },
  { name: 'கல் பாசி', category: 'grocery', unit: 'kg' },
  { name: 'கஸ்டர்ட் பொடி', category: 'grocery', unit: 'g' },
  { name: 'காபி பொடி', category: 'grocery', unit: 'g' },
  { name: 'காராமணி', category: 'grocery', unit: 'kg' },
  { name: 'கார்ன் ஃப்ளேக்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'கார்ன் ஃப்ளோர்', category: 'grocery', unit: 'g' },
  { name: 'காலிஃபிளவர்', category: 'vegetable', unit: 'kg' },
  { name: 'காளான்', category: 'vegetable', unit: 'kg' },
  { name: 'காஷ்மீரி மிளகாய் பொடி', category: 'grocery', unit: 'g' },
  { name: 'கிராம்பு', category: 'grocery', unit: 'g' },
  { name: 'கிஸ்மிஸ்', category: 'grocery', unit: 'g' },
  { name: 'கீரை', category: 'vegetable', unit: 'g' },
  { name: 'குங்குமப்பூ', category: 'grocery', unit: 'kg' },
  { name: 'குடிக்கும் சாக்லேட்', category: 'grocery', unit: 'kg' },
  { name: 'குடைமிளகாய்', category: 'vegetable', unit: 'kg' },
  { name: 'குட்டி உருளைக்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'குட்டி கத்தரிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'கும்மாய மாவு', category: 'grocery', unit: 'g' },
  { name: 'குறு மிளகு', category: 'grocery', unit: 'kg' },
  { name: 'குறுவை அரிசி மாவு', category: 'grocery', unit: 'g' },
  { name: 'குல்கந்த்', category: 'grocery', unit: 'kg' },
  { name: 'கேசரி பொடி', category: 'grocery', unit: 'g' },
  { name: 'கேப்பை மாவு', category: 'grocery', unit: 'kg' },
  { name: 'கேரட்', category: 'vegetable', unit: 'kg' },
  { name: 'கேழ்வரகு', category: 'grocery', unit: 'kg' },
  { name: 'கேழ்வரகு மாவு', category: 'grocery', unit: 'g' },
  { name: 'கையுறை', category: 'grocery', unit: 'nos' },
  { name: 'கொதித்த சீரக எடை', category: 'grocery', unit: 'kg' },
  { name: 'கொத்தமல்லி', category: 'grocery', unit: 'kg' },
  { name: 'கொத்தமல்லி இலை', category: 'vegetable', unit: 'g' },
  { name: 'கொத்தவரங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'கொள்ளு', category: 'grocery', unit: 'kg' },
  { name: 'கோக்கோ பொடி', category: 'grocery', unit: 'g' },
  { name: 'கோதாஸ் காபி பொடி', category: 'grocery', unit: 'g' },
  { name: 'கோதுமை', category: 'grocery', unit: 'kg' },
  { name: 'கோதுமை தலியா', category: 'grocery', unit: 'kg' },
  { name: 'கோதுமை பாஸ்தா', category: 'grocery', unit: 'kg' },
  { name: 'கோதுமை மாவு', category: 'grocery', unit: 'g' },
  { name: 'கோதுமை ரவை', category: 'grocery', unit: 'g' },
  { name: 'கோபி வறுவல் மாவு', category: 'grocery', unit: 'kg' },
  { name: 'கோவா (இனிப்பு இல்லாதது)', category: 'grocery', unit: 'kg' },
  { name: 'கோவைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'கோஸ்மல்லி கத்தரிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'சக்கர வரட்டி', category: 'vegetable', unit: 'kg' },
  { name: 'சக்கரைவள்ளி', category: 'vegetable', unit: 'kg' },
  { name: 'சக்கரைவள்ளிக் கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'சம்பா கோதுமை', category: 'grocery', unit: 'kg' },
  { name: 'சர்க்கரை', category: 'grocery', unit: 'g' },
  { name: 'சர்க்கரை பொடி', category: 'grocery', unit: 'g' },
  { name: 'சாட் மசாலா', category: 'grocery', unit: 'g' },
  { name: 'சாப்பாட்டு இலை', category: 'vegetable', unit: 'g' },
  { name: 'சாம்பார் டாப்பிங் பொடி', category: 'grocery', unit: 'g' },
  { name: 'சாம்பார் பொடி', category: 'grocery', unit: 'g' },
  { name: 'சாஸ் - இனிப்பு மிளகாய் சாஸ்', category: 'grocery', unit: 'g' },
  { name: 'சாஸ் - சிவப்பு மிளகாய் சாஸ்', category: 'grocery', unit: 'g' },
  { name: 'சாஸ் - செஷ்வான் சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - சோயா சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - தக்காளி சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - பாஸ்தா சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - பூண்டு சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - மயோனெய்ஸ் சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - மிளகாய் சாஸ்', category: 'grocery', unit: 'g' },
  { name: 'சாஸ் - மோமோஸ் சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சாஸ் - வெள்ளை சாஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சிங் மசாலா', category: 'grocery', unit: 'g' },
  { name: 'சின்ன சோள மாவு', category: 'grocery', unit: 'g' },
  { name: 'சின்ன வெங்காயம்', category: 'vegetable', unit: 'kg' },
  { name: 'சிப்ஸ் உருளைக்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'சிறிய அப்பளம்', category: 'grocery', unit: 'kg' },
  { name: 'சிறுதானியம் - குதிரைவாலி', category: 'grocery', unit: 'g' },
  { name: 'சிறுதானியம் - கேப்பை', category: 'grocery', unit: 'kg' },
  { name: 'சிறுதானியம் - சாமை', category: 'grocery', unit: 'kg' },
  { name: 'சிறுதானியம் - திணை', category: 'grocery', unit: 'kg' },
  { name: 'சிறுதானியம் - வரகு', category: 'grocery', unit: 'kg' },
  { name: 'சிவப்பு அவல்', category: 'grocery', unit: 'kg' },
  { name: 'சிவப்பு குடைமிளகாய்', category: 'vegetable', unit: 'kg' },
  { name: 'சிவப்பு பூசணிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'சிவப்பு மிளகாய் பூண்டு வினிகர்', category: 'grocery', unit: 'litre' },
  { name: 'சீசி கார்ன் நகெட்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சீரகப் பொடி', category: 'grocery', unit: 'g' },
  { name: 'சீரகம்', category: 'grocery', unit: 'g' },
  { name: 'சுக்கு', category: 'grocery', unit: 'kg' },
  { name: 'சுக்கு மல்லி', category: 'grocery', unit: 'kg' },
  { name: 'சுண்டைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'சுபல் கத்தரிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'சுரைக்காய்', category: 'vegetable', unit: 'nos' },
  { name: 'செர்ரி', category: 'grocery', unit: 'kg' },
  { name: 'செலரி உப்பு', category: 'grocery', unit: 'g' },
  { name: 'செஷ்வான் சட்னி (ரிதா அரோரா)', category: 'grocery', unit: 'kg' },
  { name: 'சேனைக்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'சேப்பங்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'சைனா கிராஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சோம்பு', category: 'grocery', unit: 'g' },
  { name: 'சோம்பு பொடி', category: 'grocery', unit: 'g' },
  { name: 'சோயா சங்', category: 'grocery', unit: 'kg' },
  { name: 'சோயா பீன்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'சோயா மாவு', category: 'grocery', unit: 'g' },
  { name: 'சோள மாவு', category: 'grocery', unit: 'kg' },
  { name: 'சோள ரவை', category: 'grocery', unit: 'g' },
  { name: 'சௌ சௌ', category: 'vegetable', unit: 'kg' },
  { name: 'ஜல் ஜீரா', category: 'grocery', unit: 'kg' },
  { name: 'ஜாதிக்காய்', category: 'grocery', unit: 'kg' },
  { name: 'ஜாதிக்காய் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஜாதிப்பத்திரி', category: 'grocery', unit: 'kg' },
  { name: 'ஜாதிப்பத்திரி பொடி', category: 'grocery', unit: 'g' },
  { name: 'ஜாம்', category: 'grocery', unit: 'kg' },
  { name: 'டாங்', category: 'grocery', unit: 'kg' },
  { name: 'டாடா உப்பு', category: 'grocery', unit: 'g' },
  { name: 'டிபன் தட்டு இலை', category: 'vegetable', unit: 'g' },
  { name: 'டூட்டி ஃப்ரூட்டி', category: 'grocery', unit: 'kg' },
  { name: 'டைமண்ட் கற்கண்டு', category: 'grocery', unit: 'kg' },
  { name: 'ட்ரூ சேமியா', category: 'grocery', unit: 'kg' },
  { name: 'தக்காளி (நறுக்கியது)', category: 'vegetable', unit: 'kg' },
  { name: 'தக்காளி கெட்சப்', category: 'grocery', unit: 'kg' },
  { name: 'தக்காளி தொக்கு', category: 'grocery', unit: 'kg' },
  { name: 'தக்காளி பேஸ்ட்', category: 'grocery', unit: 'kg' },
  { name: 'தட்டை அவரைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'தட்டைப்பயத்தங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'தனியா', category: 'grocery', unit: 'kg' },
  { name: 'தனியா பொடி', category: 'grocery', unit: 'g' },
  { name: 'தயிர்', category: 'vegetable', unit: 'litre' },
  { name: 'தர்பூசணி விதை', category: 'grocery', unit: 'litre' },
  { name: 'தாளிப்பு வடகம்', category: 'grocery', unit: 'kg' },
  { name: 'தேங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'தேங்காய் கிரீம்', category: 'grocery', unit: 'litre' },
  { name: 'தேங்காய் பால்', category: 'grocery', unit: 'litre' },
  { name: 'தேநீர்', category: 'grocery', unit: 'kg' },
  { name: 'தேன்', category: 'grocery', unit: 'kg' },
  { name: 'நவீன் நறுக்கிய தக்காளி', category: 'vegetable', unit: 'kg' },
  { name: 'நாட்டு சர்க்கரை', category: 'grocery', unit: 'kg' },
  { name: 'நியூட்ரியண்ட் மாவு', category: 'grocery', unit: 'kg' },
  { name: 'நிலவேம்பு', category: 'grocery', unit: 'kg' },
  { name: 'நீளமான புடலங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'நூடுல்ஸ் - சீன நூடுல்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'நூடுல்ஸ் - மேகி நூடுல்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'நூல்கோல்', category: 'vegetable', unit: 'kg' },
  { name: 'நெய்', category: 'grocery', unit: 'g' },
  { name: 'பசலைக்கீரை', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சரிசி மாவு', category: 'grocery', unit: 'g' },
  { name: 'பச்சை சுக்கினி', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சை டபுள் பீன்ஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சை பலாக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சை மாங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சை மிளகாய்', category: 'vegetable', unit: 'g' },
  { name: 'பச்சை மொச்சை', category: 'vegetable', unit: 'kg' },
  { name: 'பச்சை வேர்க்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பச்சைப் பட்டாணி', category: 'vegetable', unit: 'kg' },
  { name: 'பஜா மசாலா', category: 'grocery', unit: 'g' },
  { name: 'பஜ்ஜி மிளகாய்', category: 'vegetable', unit: 'g' },
  { name: 'பட்டர் பீன்ஸ்', category: 'vegetable', unit: 'g' },
  { name: 'பட்டை', category: 'grocery', unit: 'kg' },
  { name: 'பனீர்', category: 'grocery', unit: 'kg' },
  { name: 'பனீர் திராட்சை', category: 'vegetable', unit: 'kg' },
  { name: 'பனை கற்கண்டு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - இட்லிக்கான உளுந்து', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - உளுந்து', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - கடலைப் பருப்பு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - கருப்பு உளுந்து', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - கருப்பு கொண்டைக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - சிறிய வெள்ளை கொண்டைக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - சிவப்பு தட்டைப்பயறு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - தாளிப்புக்கான உளுந்து', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - துவரம் பருப்பு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - பட்டாணி பருப்பு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - பாசிப்பயறு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - பாசிப்பருப்பு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - பொட்டுக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - மசூர் பருப்பு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - முளைகட்டிய பாசிப்பயறு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - மொச்சை', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - ராஜ்மா', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - வெள்ளை கொண்டைக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - வெள்ளை சோயா', category: 'grocery', unit: 'kg' },
  { name: 'பருப்பு - வெள்ளை தட்டைப்பயறு', category: 'grocery', unit: 'kg' },
  { name: 'பருப்புக்கீரை', category: 'vegetable', unit: 'g' },
  { name: 'பழம் - மாம்பழம்', category: 'vegetable', unit: 'kg' },
  { name: 'பழுத்த பச்சை மிளகாய்', category: 'vegetable', unit: 'kg' },
  { name: 'பாகற்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'பாங்கோ பிரெட் தூள்', category: 'grocery', unit: 'kg' },
  { name: 'பாசுந்தி', category: 'grocery', unit: 'kg' },
  { name: 'பாதாம்', category: 'grocery', unit: 'g' },
  { name: 'பாதாம் பிசின்', category: 'grocery', unit: 'kg' },
  { name: 'பாப்படம்', category: 'grocery', unit: 'kg' },
  { name: 'பாப்ரிகா பொடி', category: 'grocery', unit: 'g' },
  { name: 'பாயாசம் காய்ச்சிய அளவு', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - கருங்குறுவை', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - காட்டுயானம்', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - தூயமல்லி அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - நவரா', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - பூங்கார்', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - மாப்பிள்ளை சம்பா', category: 'grocery', unit: 'kg' },
  { name: 'பாரம்பரிய அரிசி - மூங்கில் அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'பார்லி', category: 'grocery', unit: 'kg' },
  { name: 'பார்ஸ்லி', category: 'grocery', unit: 'kg' },
  { name: 'பாலடா', category: 'grocery', unit: 'kg' },
  { name: 'பால் (பிரவுன் பாக்கெட்)', category: 'vegetable', unit: 'litre' },
  { name: 'பால் - பால்', category: 'vegetable', unit: 'litre' },
  { name: 'பால் - பால் (ஆரஞ்சு பாக்கெட்)', category: 'vegetable', unit: 'litre' },
  { name: 'பாவ் பன்', category: 'grocery', unit: 'kg' },
  { name: 'பாஸ்தா - ஃபார்ஃபாலே', category: 'grocery', unit: 'kg' },
  { name: 'பாஸ்தா - ஃபுசில்லி', category: 'grocery', unit: 'kg' },
  { name: 'பாஸ்தா - மக்கரோனி', category: 'grocery', unit: 'kg' },
  { name: 'பிரவுன் சர்க்கரை', category: 'grocery', unit: 'g' },
  { name: 'பிரியாணி இலை', category: 'grocery', unit: 'g' },
  { name: 'பிரியாணி இலை பொடி', category: 'grocery', unit: 'g' },
  { name: 'பிரெட்', category: 'grocery', unit: 'kg' },
  { name: 'பிரோக்கோலி', category: 'vegetable', unit: 'kg' },
  { name: 'பிலாக்கொட்டை', category: 'vegetable', unit: 'kg' },
  { name: 'பீட்சா சீசனிங் பொடி', category: 'grocery', unit: 'g' },
  { name: 'பீட்ரூட்', category: 'vegetable', unit: 'kg' },
  { name: 'பீன்ஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'பீர்க்கங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'புடலங்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'புதினா இலை', category: 'vegetable', unit: 'g' },
  { name: 'புதிய கிரீம்', category: 'grocery', unit: 'litre' },
  { name: 'புளி', category: 'grocery', unit: 'kg' },
  { name: 'புளிக் குழம்பு பொடி', category: 'grocery', unit: 'g' },
  { name: 'புஷ் சிவப்பு கலர்', category: 'grocery', unit: 'kg' },
  { name: 'பூசணி விதை', category: 'grocery', unit: 'g' },
  { name: 'பூசணிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'பூண்டு', category: 'vegetable', unit: 'kg' },
  { name: 'பூண்டு ஃப்ளேக்ஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'பூண்டு பொடி ஊறுகாய்', category: 'grocery', unit: 'g' },
  { name: 'பெங்களூர் புளி', category: 'grocery', unit: 'kg' },
  { name: 'பெரிய அப்பளம்', category: 'grocery', unit: 'kg' },
  { name: 'பெரிய ரவை', category: 'grocery', unit: 'g' },
  { name: 'பெருங்காயம்', category: 'grocery', unit: 'kg' },
  { name: 'பேக்கிங் சோடா', category: 'grocery', unit: 'kg' },
  { name: 'பேக்கிங் பவுடர்', category: 'grocery', unit: 'g' },
  { name: 'பேசில்', category: 'grocery', unit: 'kg' },
  { name: 'பேபி கார்ன்', category: 'vegetable', unit: 'kg' },
  { name: 'பேபி கார்ன் பெட்டி', category: 'vegetable', unit: 'nos' },
  { name: 'பேபி கார்ன், காளான் வறுவல் மாவு', category: 'grocery', unit: 'g' },
  { name: 'பேரீச்சம் பழம்', category: 'grocery', unit: 'g' },
  { name: 'பொடியாக நறுக்கிய பூண்டு', category: 'grocery', unit: 'g' },
  { name: 'பொட்டுக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'பொன்னாங்கண்ணி கீரை', category: 'vegetable', unit: 'g' },
  { name: 'பொரி', category: 'grocery', unit: 'kg' },
  { name: 'பொரித்த பகோடா', category: 'grocery', unit: 'kg' },
  { name: 'பொரியல் பொடி', category: 'grocery', unit: 'g' },
  { name: 'போர்ன்விட்டா', category: 'grocery', unit: 'kg' },
  { name: 'மக்காச்சோளம்', category: 'grocery', unit: 'kg' },
  { name: 'மசாலா பால் பொடி', category: 'grocery', unit: 'g' },
  { name: 'மஞ்சள் குடைமிளகாய்', category: 'vegetable', unit: 'kg' },
  { name: 'மஞ்சள் சுக்கினி', category: 'vegetable', unit: 'kg' },
  { name: 'மஞ்சள் பொடி', category: 'grocery', unit: 'g' },
  { name: 'மஞ்சூரியன் மாவு', category: 'grocery', unit: 'g' },
  { name: 'மணத்தக்காளி', category: 'grocery', unit: 'kg' },
  { name: 'மணத்தக்காளி கீரை', category: 'vegetable', unit: 'g' },
  { name: 'மண்டா வெல்லம்', category: 'grocery', unit: 'kg' },
  { name: 'மயோனெய்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'மரவள்ளிக்கிழங்கு', category: 'vegetable', unit: 'kg' },
  { name: 'மாங்காய் இஞ்சி', category: 'vegetable', unit: 'kg' },
  { name: 'மாதுளம்பழம்', category: 'vegetable', unit: 'kg' },
  { name: 'மாதுளை பொடி', category: 'grocery', unit: 'g' },
  { name: 'மாதுளை விதை பொடி', category: 'grocery', unit: 'g' },
  { name: 'மாவு ஜவ்வரிசி', category: 'grocery', unit: 'g' },
  { name: 'மாஸ் பாதாம் மிக்ஸ்', category: 'grocery', unit: 'g' },
  { name: 'மில்கி மிஸ்ட் பனீர்', category: 'vegetable', unit: 'litre' },
  { name: 'மிளகாய் - சம்பா மிளகாய்', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் - சிவப்பு மிளகாய்', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் - சிவப்பு மிளகாய் (புதியது)', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் - வட இந்திய மிளகாய்', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் பொடி', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் பொடி (CATCH)', category: 'grocery', unit: 'g' },
  { name: 'மிளகாய் பொடி (NEW)', category: 'grocery', unit: 'g' },
  { name: 'மிளகு', category: 'grocery', unit: 'g' },
  { name: 'மிளகு பொடி', category: 'grocery', unit: 'g' },
  { name: 'மிளகு, சீரகப் பொடி', category: 'grocery', unit: 'g' },
  { name: 'மீல் மேக்கர்', category: 'grocery', unit: 'kg' },
  { name: 'முடக்கத்தான் கீரை', category: 'vegetable', unit: 'g' },
  { name: 'முட்டைக்கோஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'முதல் தர முந்திரி', category: 'grocery', unit: 'g' },
  { name: 'முந்திரி', category: 'grocery', unit: 'g' },
  { name: 'முருங்கைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'முருங்கைக்கீரை', category: 'vegetable', unit: 'g' },
  { name: 'முள்ளங்கி', category: 'vegetable', unit: 'kg' },
  { name: 'முழு கரம் மசாலா', category: 'grocery', unit: 'g' },
  { name: 'மெட்ராஸ் கரி பொடி', category: 'grocery', unit: 'g' },
  { name: 'மேகி க்யூப்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'மைதா மாவு', category: 'grocery', unit: 'kg' },
  { name: 'ரசப் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ரசமலாய்', category: 'vegetable', unit: 'kg' },
  { name: 'ரவை மிக்ஸ்', category: 'grocery', unit: 'g' },
  { name: 'ரஸ்க் பொடி', category: 'grocery', unit: 'g' },
  { name: 'ரெடிமேட் பூரி', category: 'grocery', unit: 'kg' },
  { name: 'ரோஸ் எசன்ஸ்', category: 'grocery', unit: 'litre' },
  { name: 'லயன் பேரீச்சம் பழ சிரப்', category: 'grocery', unit: 'litre' },
  { name: 'லிஜ்ஜத் பாப்பட்', category: 'grocery', unit: 'kg' },
  { name: 'லெட்ச கெட்ட கீரை', category: 'vegetable', unit: 'g' },
  { name: 'லெவிஸ்டா காபி பொடி', category: 'grocery', unit: 'g' },
  { name: 'வதக்கிய எடை', category: 'vegetable', unit: 'kg' },
  { name: 'வத்தல் - மோர் மிளகாய்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் அப்பளப் பூ', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் அவரை', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் இதயம்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் உளுந்து', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் ஓமப்பொடி வடம்', category: 'grocery', unit: 'g' },
  { name: 'வத்தல் கத்தரிக்காய்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் கார்ன் ஃப்ளேக்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் கூழ்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் கொத்தவரங்காய்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் சீனீஸ் போர்டர்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் சீரியல் ரவுண்ட்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் சுண்டைக்காய்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் ஜவ்வரிசி நாணயம்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் டைமண்ட்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் நிலா', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் நீட்டு', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் பானி பூரி', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் பூண்டு', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் பேட்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் மாவத்தல்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் மிளகாய்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் முக்கோணம்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் முறுக்கு', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் வெங்காயம்', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் வெள்ளை சூர்யா', category: 'grocery', unit: 'kg' },
  { name: 'வத்தல் வெள்ளை ரிங்', category: 'grocery', unit: 'kg' },
  { name: 'வரகு', category: 'grocery', unit: 'kg' },
  { name: 'வறுத்த கொண்டைக்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'வறுத்த சீரகப் பொடி', category: 'grocery', unit: 'g' },
  { name: 'வறுத்த பாம்பினோ சேமியா', category: 'grocery', unit: 'kg' },
  { name: 'வறுத்த மிளகு பொடி', category: 'grocery', unit: 'g' },
  { name: 'வறுத்த வெள்ளை எள்', category: 'grocery', unit: 'g' },
  { name: 'வறுத்த வேர்க்கடலை', category: 'grocery', unit: 'g' },
  { name: 'வறுத்து அரைத்த கோதுமை மாவு', category: 'grocery', unit: 'kg' },
  { name: 'வாழை இலை', category: 'vegetable', unit: 'g' },
  { name: 'வாழைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'வாழைத்தண்டு', category: 'vegetable', unit: 'kg' },
  { name: 'வாழைப்பட்டை', category: 'vegetable', unit: 'kg' },
  { name: 'வாழைப்பழம்', category: 'vegetable', unit: 'kg' },
  { name: 'வாழைப்பூ', category: 'vegetable', unit: 'kg' },
  { name: 'வினிகர்', category: 'grocery', unit: 'litre' },
  { name: 'விரலி மஞ்சள்', category: 'grocery', unit: 'kg' },
  { name: 'வெங்காய ஃப்ளேக்ஸ்', category: 'vegetable', unit: 'kg' },
  { name: 'வெங்காய வத்தல்', category: 'grocery', unit: 'kg' },
  { name: 'வெங்காய விதை', category: 'grocery', unit: 'g' },
  { name: 'வெங்காயப் பொடி', category: 'grocery', unit: 'g' },
  { name: 'வெங்காயம்', category: 'vegetable', unit: 'kg' },
  { name: 'வெண்டைக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'வெந்தய இலை', category: 'vegetable', unit: 'g' },
  { name: 'வெந்தயம்', category: 'grocery', unit: 'kg' },
  { name: 'வெனிலா எசன்ஸ்', category: 'grocery', unit: 'litre' },
  { name: 'வெள்ளரி விதை', category: 'grocery', unit: 'g' },
  { name: 'வெள்ளரிக்காய்', category: 'vegetable', unit: 'kg' },
  { name: 'வெள்ளை எள்', category: 'grocery', unit: 'g' },
  { name: 'வெள்ளை கவுனி அரிசி', category: 'grocery', unit: 'kg' },
  { name: 'வெள்ளை சோளம்', category: 'grocery', unit: 'kg' },
  { name: 'வெள்ளை பட்டாணி', category: 'grocery', unit: 'kg' },
  { name: 'வெள்ளை மிளகு', category: 'grocery', unit: 'g' },
  { name: 'வேப்பம்பூ', category: 'vegetable', unit: 'kg' },
  { name: 'வேர்க்கடலை', category: 'grocery', unit: 'kg' },
  { name: 'ஸ்டார்டர் - சீசி கார்ன் நகெட்ஸ்', category: 'grocery', unit: 'kg' },
  { name: 'ஸ்பிரிங் ஆனியன் பச்சை பகுதி', category: 'vegetable', unit: 'kg' },
  { name: 'ஸ்பிரிங் ஆனியன் வெள்ளை பகுதி', category: 'vegetable', unit: 'kg' },
  { name: 'ஹட்சன் தயிர்', category: 'vegetable', unit: 'litre' },
  { name: 'ஹட்சன் தயிர் பெட்டி', category: 'vegetable', unit: 'litre' },
];
